### ISSUE TITLE
Doesn't seem to work with Python 2.x, only with Python3.x

### ISSUE THREAD

**Issue by lstep** [timothycrosley/hug#110]
It uses a mock module that doesn't seem to exist in Python 2. When using Python3 it works fine.
Is this project supposed to be Python3 only?

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import hug
  File "/usr/local/lib/python2.7/dist-packages/hug/__init__.py", line 32, in <module>
    from hug import (authentication, directives, documentation, exceptions, format,
  File "/usr/local/lib/python2.7/dist-packages/hug/test.py", line 26, in <module>
    from unittest import mock
ImportError: cannot import name mock
```
Tried with version 1.9.3 installed using pip.

**Comment by timothycrosley** [comment]
Hi @lstep,

Yes hug is for Python 3.x *only*. The primary reason for this is that it leverages type annotations to automatically validate and convert both incoming and outgoing data for requests, something that simply is not possible with Python2. This is noted in the first section of the README on github: "As a result of these goals Hug is Python3+ only and uses Falcon under the cover to quickly handle requests."

Thanks, and I hope you find hug useless regardless!

~Timothy
