### ISSUE TITLE
Non-versioned endpoints not showing up in documentation

### ISSUE THREAD

**Issue by cy70sin3** [timothycrosley/hug#112]
If a decorator has 'versions' set all endpoints without 'versions' set do not show up in the documentation. Is this an intended feature?

**Comment by timothycrosley** [comment]
Hi @cy70sin3, 

Thanks for reporting this! No It is not the intended behavior, I'll be working on releasing a fix for this issue soon.

~Timothy

**Comment by timothycrosley** [comment]
This has been fixed in the just released on PYPI `1.9.6` version of hug.

Thanks!

~Timothy
