### ISSUE TITLE
Retrieving request body?

### ISSUE THREAD

**Issue by jmmills** [timothycrosley/hug#120]
First off, like this API simple and strait to the point.

I've used hug to build a simple REST API layer to another api, I would like to log the request body and parameters to be used at a later date for application data analytics (pretty graphs!) but there doesn't seem to be a clear way to this indicated by documentation, something as simple as this:

    import hug
    @hug.get('/version')
    def get_version();
        info(response.body);

Would suffice, is the response functions only available in the application middleware?

**Comment by timothycrosley** [comment]
Hi,

@jmmills,

Hug automatically passes a long a request and or body parameter if they are requested, you can see an example of this here:

https://github.com/timothycrosley/hug/blob/develop/examples/post_body_example.py

So, for your exact question, the implementation would be:

    import hug

    @hug.get('/version')
    def get_version(body=None):
        print(body)

`body` in this case will automatically be turned into a Python object representation of the passed data for easy parsing, assuming it is JSON.

Let me know if this resolves your issue. Thanks!

~Timothy

**Comment by jmmills** [comment]
Awesome, thanks.

I ended up just doing it in a request middleware call since I needed to create a default response header.


Thanks,
   Jason Mills

- sent from mobile.

**Comment by timothycrosley** [comment]
Glad you were able to find a resolution to your issue :)
