### ISSUE TITLE
Add a guide on how to build hug extensions / plugins

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/hug#152]
In order to encourage more modules to be built that extend hug capabilities it would be useful to build a guiding document that describes the process to extend and use hug extensions.

**Comment by horvathcom** [comment]
Just starting with hug.  Was wondering how I might add OAuth 2.0 Bearer tokens to authenticate requests.   Some may be able to use introspection of JWTs if that is what the authorization server uses, or making a call to a validation endpoint for reference tokens.

**Comment by timothycrosley** [comment]
Initial guide for building hug extensions has been added: https://github.com/timothycrosley/hug/blob/develop/EXTENDING.md
