### ISSUE TITLE
Ability to route separate from handlers

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/hug#162]
It would be useful to enable routing to be done separate from the handler functions to better support alternative directory structures and workflows:

api.py

    import hug
    import library

    api = hug.API(__name__)
    api.get('/api_call_1')(library.function_1)
    api.class_based('/api_calls_2')(library.class_1)

That would also allow easy routing of existing internal Python only APIs without code changes
 
It's important to note, however, that this would need to be done in addition to the default behavior of decorating functions, and would not be replacing it.

**Comment by timothycrosley** [comment]
Implementing in the form:

api.py

    import hug
    import library

    api_router = hug.APIRouter(hug.API(__name__))
    api_router.urls('/api_call_1').get()(library.function_1)

**Comment by timothycrosley** [comment]
or more simply:

api.py


    import hug
    import library

    api_router = hug.APIRouter(__name__)
    api_router.urls('/api_call_1').get()(library.function_1)

**Comment by timothycrosley** [comment]
final implementation:

    import hug
    import library

    route = hug.route.API(__name__)
    route.urls('/api_call_1').get()(library.function_1)
    route.object('/api_call_2')(library.class_1)

**Comment by SkiftCreative** [comment]
I am curious how I would use this, along with further routing.

so if I have the class from the above:
```
class class_1:
    pass
````

how would I route the HTTP verbs to given methods. Ideally, I would like to do something like:
```
class User:
    @hug.get('/')
    def get(self):
        return {[...], [...]}

    @hug.get('/{id}')
    def get_by_id(self, id: int):
        return {...}
```

which means that `get_by_id()` method would route to `/user/{id}' if I mounted the class per above:

```
import hug
import library

route = hug.route.API(__name__)
route.object('/user')(library.User)
```
