### ISSUE TITLE
PEP 257 docstrings

### ISSUE THREAD

**Issue by ianthetechie** [timothycrosley/hug#177]
The coding standards document indicates that the code in this project should conform to PEP 8, which specifies PEP 257 docstrings. My pull request #176 changed the files that it touched. I would be happy to take care of converting the rest of the project if you like.

**Comment by timothycrosley** [comment]
Thanks for notifying me about this! I didn't even realize the spec called for double quotes, the code base should certainly be updated to match the defined coding standards :)

**Comment by ianthetechie** [comment]
No worries. It's one of those things that didn't get solidified until later on anyways. I'm likewise a fan of single quotes everywhere else, since that's one less shift key press ;) Working on this right now, as well as adding unit tests for the functions added in my last PR.
