### ISSUE TITLE
Add instructions for contributing using a Windows based machine

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/hug#179]
It would be useful to list instructions on getting hug setup for development / contributing from a Windows based machine. Since I do not own any computers running Windows personally, this is an area where I could really use another contributor's help to ensure the instructions are correct.

**Comment by pferate** [comment]
I'll try taking a stab at this.  I'll need to create a windows batch file equivalent to `.env`; I'll name it `.env.cmd`, unless you want it named something else.

I don't foresee any major changes to the instructions; mainly just running `.env.cmd` instead.

**Comment by voltagex** [comment]
Files beginning with a `.` can be a pain on Windows, is there any reason not to call it `env.cmd`?

**Comment by pferate** [comment]
No strong reason.  I just figured I'd keep it as a hidden file on POSIX systems and keep the differences minimal.

**Comment by voltagex** [comment]
Fair enough

**Comment by timothycrosley** [comment]
+1 Any work that is done on this would be super appreciated / helpful :)

~Timothy

**Comment by aeroaks** [comment]
I would be interested in working on this! Might need some help though!

**Comment by aeroaks** [comment]
I tried running the tests and a simple example (given in issue #500) using 'pipenv' in Windows and can confirm that it works properly. Just a note that it asks firewall permission for the first time. Would you guys be interested in having that added to the contribution file?

**Comment by timothycrosley** [comment]
Yes! I would love to have that added!

Thanks!
~Timothy
