### ISSUE TITLE
test module has no attribute '__hug__'

### ISSUE THREAD

**Issue by fbukevin** [timothycrosley/hug#185]
I tried to test with simple code like this:
```python
# test_api.py

import hug
import app   # sample module as demo code in README

hug.test.get(app, 'json_format', {'hello': 'world'})
```

After I used `hug -f test_api.py`, the error shown up:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/bin/hug", line 11, in <module>
    sys.exit(run.terminal())
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hug/run.py", line 172, in terminal
    **server_arguments)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hug/run.py", line 118, in server
    api = falcon.API(middleware=module.__hug__.middleware)
AttributeError: module 'test_api' has no attribute '__hug__'
```

I found this [https://github.com/timothycrosley/hug/issues/180](https://github.com/timothycrosley/hug/issues/180) closed issue but it seems not the problem I found?

**Comment by timothycrosley** [comment]
Hi @fbukevin, 

It appears test_api (or `app` in your code example) does not define any hug endpoints, and is therefore not a valid endpoint to test. Any chance you can paste the contents of `app` since you said that it was just sample code provided in the README?

Thanks!

~Timothy

**Comment by fbukevin** [comment]
Hi, thanks for reply me. The code in app.py is here:

```py

"""A basic (single function) API written using Hug"""
import hug
import pymongo


@hug.get('/happy_birthday')
def happy_birthday(name, age:hug.types.number=1):
    """Says happy birthday to a user"""
    return "Happy {age} Birthday {name}!".format(**locals())


@hug.get('/json_format')
def json_format():
  return {'hello': 'world'}
```

I can access with `hug -f app.py`. But it failed as I mentioned above.

**Comment by timothycrosley** [comment]
Hi @fbukevin,

After some thought, I think I realized what issue you are running into:

The hug command line tool is *only* for running hug APIs not arbitrary code that interacts with those APIs. So in your example:

`hug -f app.py` is perfectly valid

However, for running test_api.py you should only have to do:

`python test_api.py`

This is because your test code can't reasonably be used to host an HTTP server, which is what the hug command line tool is for.

Hope this helps!

Thanks!

~Timothy

**Comment by fbukevin** [comment]
Haha, I see~ It works with `python3 test_api.py`. Thanks!
