### ISSUE TITLE
MultiPart files support

### ISSUE THREAD

**Issue by ankitml** [timothycrosley/hug#195]
How to accept file uploads in the API? Is it supported ?

**Comment by timothycrosley** [comment]
Hi @ankitml, 

Yes it is supported! And should be relatively easy:

     @hug.post()
     def my_file_uploader(body):
         file = body.read()

Is all that should be required :) Let me know if this works for you.
With body being the post body. hug automatically injects: body, request, or response when they are requested by being parameters of the function.


Thanks!

~Timothy

**Comment by timeu** [comment]
I upgraded recently from 2.0.6 to 2.1.2 and somehow multipart/form-data seems to be broken. 

From the client side I do following: 

```
var data = new FormData();
data.append('file', file);
fetch(`/api/genotype/${id}`,{method: 'POST', body: data}
```

According to Chrome Dev Tools the request seems to be fine: 

```
------WebKitFormBoundary5Xsne5Sf6WeDyNCs
Content-Disposition: form-data; name="file"; filename="somefile.txt"
Content-Type: text/plain

------WebKitFormBoundary5Xsne5Sf6WeDyNCs--
```

But `body` is empty on the backend. I am not sure if this is a hug issue or a falcon issue. Couldn't find any issue there.

**Comment by cag** [comment]
Hey @timeu, you can probably blame me. Check this pull request: https://github.com/timothycrosley/hug/pull/302

You can also override this by specifying your own multipart/form-data handler. It uses cgi.parse_multipart which may not be the best implementation available. Actually, if you have a better library for working with this data, it'd be really appreciated.

**Comment by timeu** [comment]
@cag I am not 100% sure if this is really a hug or rather a falcon issue. I will try to debug and see why `body` is empty.
