### ISSUE TITLE
Better way to add custom routes. 

### ISSUE THREAD

**Issue by Doldge** [timothycrosley/hug#199]
Firstly, I'd like to start by saying this is a great project, And I expect I'll be contributing to it in the near future.

Now for the issue. I'm trying to add a route for a function that I've defined in another file. For various reasons, I don't want to import hug into that file and then load the entire thing as a module. As best I can tell, the only way to create a route for the function is to do the following:

```python
import index
import hug

@hug.get('/')
def somefunc():
     return index.index()
```
It works, but I'd like to skip having to create a function just to call another function. For comparison, this is how to do it in flask:
```python
import index
from flask import Flask
app = Flask(__name__)

app.add_url_rule('/','index', index.index)
```

It would be nice if hug exposed some way to do a similar thing. Or If you can point me In the direction of either A) a better way to do it in hug, or B) the code I need to look at changing to expose this functionality myself.

Thanks, Callum.

**Comment by timothycrosley** [comment]
Hi @Doldge,

If you're willing to use the develop branch this works now :). You can install it by doing the following:

    pip install git+git://github.com/timothycrosley/hug.git@master

What's in development lets you do the following:

    import hug
    import index

    hug.API(__name__).get('/')(index.index)


or if your going to reuse the API object:


    import hug
    import index

    api = hug.API(__name__)
    api.get('/')(index.index)

The development branch is slated for release as 2.0.0 March 1st. Hope this is helpful!

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This was fixed here: https://github.com/timothycrosley/hug/issues/162 if you are curious
