### ISSUE TITLE
Token Authentication?

### ISSUE THREAD

**Issue by tanrax** [timothycrosley/hug#201]
This feature exists or should I do it myself?
Thank you!!

**Comment by cyberbeast** [comment]
It would be amazing if token authentication could be part of hug.

**Comment by timothycrosley** [comment]
Hug currently doesn't have token based authentication built in, but I would happily accept any pull requests that add it! Currently hug only has built in support for basic and API-key based authentication: https://github.com/timothycrosley/hug/blob/develop/hug/authentication.py Adding new authentication types should be fairly straight forward to implement however.

Thanks!

~Timothy

**Comment by nicois** [comment]
I have written a basic cookie authentication method, with active directory lookup.
The problem I see is that the hug-specific code only varies from the api key authenticator by a couple of lines. If you want to issue a session cookie, you'll either need to go down the flask route with encrypting everything client-side, or maintaining state on the server.
In my case I'm using memcached to maintain (and auto-expire) the tokens on the server, to allow multiple instances to share state. Unless hug expands its scope beyond simple API, I think HMAC is the way to do this properly.

**Comment by rodcloutier** [comment]
Looks like Hug has a basic Token authenticator:  https://github.com/timothycrosley/hug/blob/develop/hug/authentication.py#L107

What would be needed on top of this?

**Comment by timothycrosley** [comment]
@rodcloutier, 

I think that now that hug has basic token authentication included this issue can be closed out, if other more complex types of authentication methods are needed, I think they would be best implemented as hug extensions to keep hug's requirement list to a minimum.

Thanks!

~Timothy
