### ISSUE TITLE
 Change error messages

### ISSUE THREAD

**Issue by tanrax** [timothycrosley/hug#202]
It is possible to change and / or translate?

**Comment by timothycrosley** [comment]
Hi @tanrax,

What kind of error messages do you want to change / translate? Validation errors, or exceptions that occur during processing of a request?

Thanks!

~Timothy

**Comment by tanrax** [comment]
Validation errors  :)

**Comment by timothycrosley** [comment]
Currently, you can customize the text returned by errors by doing the following:

    @hug.get()
    def my_endpoint(argument:hug.types.accept(hug.types.number, error_text="Custom error text")):
        return data

additionally, in the develop branch, you can customize the overall message that is returned on validation errors by providing an `on_invalid` transformation that will take the entire {'errors:{}} dictionary for modification before returning to the user.

Let me know if this helps to resolve your issue, or if there is a better way you can think to handle this issue that could then be integrated into hug.

Thanks!

~Timothy

**Comment by tanrax** [comment]
Many thanks!
This information would be great in the wiki :)
