### ISSUE TITLE
running api with gunicorn

### ISSUE THREAD

**Issue by nathanbraun** [timothycrosley/hug#205]
Hi there, thanks for all your work on this, looks great.  I'm a bit confused on how to run the API on other WSGI servers though.  For example, how would I run the happy_birthday.py example on gunicorn?

THanks!

**Comment by timothycrosley** [comment]
Hi @nathanbraun:

Thanks! Running on gunicorn should be fairly straight forward:

`gunicorn hello_world:__hug_wsgi__`

in the case of the Hello world example. The key is that hug automatically creates the WSGI compatible application as `__hug_wsgi__` on any module that contains hugged functions.

Hopefully this helpful,

Thanks!

~Timothy
