### ISSUE TITLE
APIs with arguments as part of the HTTP path

### ISSUE THREAD

**Issue by andymccurdy** [timothycrosley/hug#207]
I didn't see anything in the docs about creating HTTP endpoints where arguments are part of the path. For instance, `/user/<user_id>`.

Is this supported and I'm missing it? If it isn't currently supported, would this functionality be welcomed?

**Comment by timothycrosley** [comment]
Hi @andymccurdy yes this is supported!

You can simply do `/user/{user_id}/' as your url route, and user_id will automatically get passed to the decorated function.

Thanks!

~Timothy

**Comment by andymccurdy** [comment]
Thanks for the quick response!
