### ISSUE TITLE
Run as WSGI app in Tornado

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#209]
Hi,

I'm looking to run hug as a WSGI app in my tornado web-server, but I'm having a hard time "getting" the WSGI app from hug. It seems like you're expecting the python file containing the api definitions to be taken as the wsgi file, however I have yet to find a way to explicitly get or create a wsgi application python object from it.. Any help would be much appreciated! My current, minimalistic, set-up:

api.py
```
import hug

@hug.get('/echo')
def hello_world():
    return {"hello": "world"}
```

runserver.py
```
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop
from tornado.web import Application, FallbackHandler
from tornado.wsgi import WSGIContainer

import api

if __name__ == "__main__":
    port = 8000
    container_hug = WSGIContainer(api.__hug_wsgi__)
    tornado_app = Application(
            [
                ('.*', FallbackHandler, dict(fallback=container_hug)),
            ])
    http_server = HTTPServer(tornado_app)
    http_server.listen(port)
    IOLoop.instance().start()

```
Then running:

    python3  runserver.py

But obviously this doesn't work.. What would I need to change to make it work?

Thanks in advance!

Best,

Erwin

**Comment by ErwinHaasnoot** [comment]
Actually, I think I have figured it out. i'm not sure if this is the intended way to do it though?

Update runserver.py
```
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop
from tornado.web import Application, FallbackHandler
from tornado.wsgi import WSGIContainer

import api
from hug.run import server

if __name__ == "__main__":
    port = 8000
    container_hug = WSGIContainer(server(api))
    tornado_app = Application(
            [
                ('.*', FallbackHandler, dict(fallback=container_hug)),
            ])
    http_server = HTTPServer(tornado_app)
    http_server.listen(port)
    IOLoop.instance().start()
```

now doing 

    curl http://localhost:8000/echo

returns

    {"hello": "world"}

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

That's the correct way to do it, and obviously needs more documentation :) I'm kinda surprised __hug_wsgi__ didn't work all on it's own, but I guess tornado must be doing some introspection work on it instead of just passing in the UWSGI commands.

Thanks!

~Timothy

**Comment by SkiftCreative** [comment]
Thats great as I was thinking about tornado last night. I am not quite ready for it but would be great to get a code sample in the docs somewhere.

**Comment by ErwinHaasnoot** [comment]
Another note. There seems to be a major difference between using the following ways to run a minimal tornado app. The method I mentioned above in my previous post DOES NOT WORK.

You need to wrap your module inside the hug API class, as following:

```
from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop
from tornado.web import Application, FallbackHandler
from tornado.wsgi import WSGIContainer

import hug_api_test as api
from hug import API
from hug.run import server

if __name__ == "__main__":
    port = 8000
    container_hug = WSGIContainer(server(API(api)))
    tornado_app = Application(
            [
                ('.*', FallbackHandler, dict(fallback=container_hug)),
            ])
    http_server = HTTPServer(tornado_app)
    http_server.listen(port)
    IOLoop.instance().start()

```
