### ISSUE TITLE
Make Hug API with base url path other than root '/'

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#210]
Hi! 

My second issue of the day. Either I'm missing something, or this has not been implemented yet. I'd like to have the Hug API work relatively from a certain base path (default to root '/'), but am again having a hard time figuring it out. There doesn't seem to be any support for it, as far as I can tell?

Say I have the following API function
```
@hug.get('/stuff')
def stuff():
    return {"hello":"world"}

```
and run the hug server on localhost 8000, I'd be able to use the following curl command:

    curl http://localhost:8000/stuff/

to perform a GET request on the API function I just defined.

if I add versioning, it becomes
```
@hug.get('/stuff',versions=1)
def stuff():
    return {"hello":"world"}
```

and now I have to point curl to

    curl http://localhost:8000/v1/stuff/

However, this doesn't really play nicely when I want to run my hug API as part of a bigger webserver, such as in my previous question #209.

For example, if I want to use a base_path '/api', so that (in my case) tornado can re-direct all http requests that start with '/api' in the url path to the hug WSGI application, I can add '/api' to every path in the decorators, like so:
```
@hug.get('/api/stuff')
def stuff():
    return {"hello":"world"}
```
 
which I'd be able to reach with curl on

    curl http://localhost:8000/api/stuff/

BUT, this stops working when I introduce versioning

```
@hug.get('/api/stuff',versions=1)
def stuff():
    return {"hello":"world"}
```

which I'd be able to reach with curl on

    curl http://localhost:8000/v1/api/stuff/

breaking the pattern rule I had set-up for Tornado.

Is there anyway to get this working?

Thanks a lot!

Best,

Erwin

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

The easiest way to solve your issue short-term is to the 'X-API-VERSION' to request different versions instead of the '/v1' url prefix.

Unfortunately, hug does assume that it's running on the root path currently. I would be very happy to see the ability to set the root path on the API object to enable this, and would very quickly accept a pull request that adds that feature. Either way, I'll make sure it gets into the hug 2.0.0 release slated for March 1st.

Thanks!

~Timothy Crosley

**Comment by ErwinHaasnoot** [comment]
Hi @timothycrosley,

Thanks for all your work, I love the experience of developing a hug API so far. I'll try and see if I can implement the feature myself and submit a pull request, but I'm not sure if I'll have time. 

Luckily the API I'm working on is not yet slated for public release, so right now it does not need versioning information, but it will be good to implement asap. 

Best,

Erwin

**Comment by geoffjukes** [comment]
If you use nGinx in front of the API, just add a location rule with a rewrite, for example:
```
location /api {
        rewrite ^/api/?(.*)$ /$1 break;
        #forward to HUG API
        uwsgi_pass unix:///tmp/api.uwsgi.sock;
        include uwsgi_params;

    }
```

Then Hug doesn't need to care about the root prefix, and the versioning etc all works as normal.

**Comment by geoffjukes** [comment]
As mentioned in #495, this is now possible in Hug 2.0
`hug.API(__name__).http.base_url = '/subdir'`
Make sure you do this OR the nginx rewrite (not both!)
