### ISSUE TITLE
Text Types treated as list when text param use comma 

### ISSUE THREAD

**Issue by bguzryanto** [timothycrosley/hug#212]
```python
@hug.get('/assert_text')
def assert_text(text, text_with_hug_types:hug.types.text):
  return {
    text: text,
    text: text_with_hug_types
  }
````
Request URL
> 127.0.0.1/assert_text?text=this,is,should,be,text&text_with_hug_types=this,is,should,be,text

Result: 
```json
{
  "text": [
  "this",
  "is",
  "should",
  "be",
  "text"
  ],
  "text_with_hug_types": "['this', 'is', 'should', 'be', 'text']"
}
```

text_with_hug_types should be `this,is,should,be,text` instead of `['this', 'is', 'should', 'be', 'text']`

**Comment by BrandonHoffman** [comment]
@bguzryanto I actually do not think this is a bug with the hug type. According to RFC 3986 comma is a delimiter and therefore is treated that way by the server. Easy fix should be to URL encode your parameters, commas would be replaced with %2C if your desired result is "this,is,should,be,text" or change the type of you parameter to a hug.types.Multiple if your desired result is ['this', 'is', 'should','be','text']. 

@timothycrosley my only real suggestion here is that we might want to add validation to the text type and make it throw an error for only expecting a single parameter and receiving multiple.

**Comment by timothycrosley** [comment]
I've resolved this issue by correctly throwing an exception / validation error when a list is provided to the string type. If there is a desire to have this work in the way you initially expected, you could create a custom type for it:


    def joined_string(string):
        return ",".join(string) if type(string) in (tuple, list) else str(string)

Thanks!

~Timothy

**Comment by bguzryanto** [comment]
@timothycrosley  yes, my current workaround using something like you suggested. Thanks
