### ISSUE TITLE
Add Python's UUID as a hug type

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#215]
Hi!

My first attempt at contributing. UUIDs seem like a major component of any web-based API nowadays, so having a type that specifically checks if given parameters are UUIDs, rather than simple strings, seems to me like a good type to have out-of-the-box?

I'll be submitting a Pull Request for this soon, so please confirm/deny as you see fit!

**Comment by timothycrosley** [comment]
Thanks for the contribution! I agree that this will be very useful

~Timothy
