### ISSUE TITLE
Use Github Issue Milestones to show what is going into a next release

### ISSUE THREAD

**Issue by SkiftCreative** [timothycrosley/hug#217]
I am curious if you could use the github milestones to tags issues for 2.0 release to make it easier to follow what issues are being pushed into 2.0 (or whatever new version is coming up)? I think it would make it easier for people to see what new code, features, or bug fixes are going into a release. As well as potential release dates or progress on that milestone. 

I know you wouldn't want to go back and tag existing or closed items to the milestone, but I think it could be beneficial to see that for community members.

**Comment by timothycrosley** [comment]
Agreed, I'll start switching over to this process, I think it will be super helpful going forward

**Comment by SkiftCreative** [comment]
Sweet. Thanks.
