### ISSUE TITLE
Output directives not passing the correct values in some cases?

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#226]
Hi again!

It seems like output types are now correctly appearing in the documentation, so thanks for that! It also seems like directives doc strings are taken as type explanations, which is great! But something's a bit wonky about the output type directives. I think it explicitly checks if positional argument "catch-all" are available? And depending on that will pass in different arguments?

For example, my favourite API
```
import hug

@hug.directive()
def custom_directive(*args,**kwargs):
     return str(args[0])

@hug.get('/')
def stuff() -> custom_directive:
    return "hello"
```

If I run the server and call my root API function, hello returned.

However, if I run the following instead:
```
import hug

@hug.directive()
def custom_directive(hello,**kwargs):
     print(kwargs)
     return hello

@hug.get('/')
def stuff() -> custom_directive:
    return "hello"
```

I get an error on my server saying:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1422, in _execute
    result = self.prepare()
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 2681, in prepare
    self.fallback(self.request)
  File "/usr/local/lib/python3.5/dist-packages/tornado/wsgi.py", line 277, in __call__
    WSGIContainer.environ(request), start_response)
  File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 182, in __call__
    responder(req, resp, **params)
  File "/home/erwin/Workspace/repositories/eid-idp-ubiqu/hug/interface.py", line 533, in __call__
    input_parameters = self.gather_parameters(request, response, api_version, **kwargs)
  File "/home/erwin/Workspace/repositories/eid-idp-ubiqu/hug/interface.py", line 419, in gather_parameters
    module=self.api.module, api_version=api_version)
TypeError: custom_directive() missing 1 required positional argument: 'hello'
```

and then, if I add a default value for my `hello` arg
```
import hug

@hug.directive()
def custom_directive(hello="world",**kwargs):
     print(kwargs)
     return hello

@hug.get('/')
def stuff() -> custom_directive:
    return "hello"
```

"world" is returned instead, and my kwargs is filled with the fields 'response','request', 'module' and 'api_version'

Any idea what's going on here?

Thanks!

Erwin

**Comment by ErwinHaasnoot** [comment]
Ah actually, the directive seems to be called twice? Once with the kwargs with weird values, and once with the actual value in args?

I've written a decorator wrapper that filters out the first call, with the filled kwargs:
```
import hug

def fix_double_call_wrapper(fn):
    def f(*args, **kwargs):
        if len(kwargs) > 0:
            return None
        else:
            return fn(args[0])
    return f

@hug.directive()
@fix_double_call_wrapper
def custom_directive(hello):
     return hello

@hug.get('/')
def stuff() -> custom_directive:
    return "hello"
```

Works..

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

Hmm I'll have to take a look at this one once I get back home from work, but I will say, I never expected directives to be used as an output annotation, what is it that you want the directive to accomplish? I wonder if you could fix your issue just by removing the `@directive` decorator?

Thanks!

~Timothy

**Comment by ErwinHaasnoot** [comment]
I want to do some postprocessing on the outout. Many of my functions return
different instances of the same (django) model and directives seemed like a
good fit to take the model and return proper output. Which is what the
documentation led me to believe it is for?

As a side note, it seems to also give me any output, even if its only
errors?

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

I think it's a miscommunication of my documentation, if you simply want to change the output all you need to do is define a function that takes the output and then transforms it and returns it. Here is an example that will transform any output data to be wrapped in a results dict:


    def wrap_in_results(output):
         return {'results': output}

    @hug.get()
    def my_endpoint() -> wrap_in_results:
         return [1, 2, 3]

Any calls to this will return {'results': output} from the command line.
You can then add request, response etc to your transforming function if you need to introspect them in order to know how to transform the data, and they will be automatically passed in and provided.

Let me know if this works for you :)

Thanks!

~Timothy

**Comment by ErwinHaasnoot** [comment]
Hi @timothycrosley,

Aha. I figured it would work symmetrically to:

```
@hug.directive()
def square(value=1, **kwargs):
    '''Returns passed in parameter multiplied by itself'''
    return value * value

@hug.get()
def tester(value: square=10):
    return value

tester() == 100
```

but for output, rather than input.

I'll try the method you suggested! Thanks!

Best,

Erwin

**Comment by ErwinHaasnoot** [comment]
To get back to you, this seems to work, there's no double calling going on anymore, but I do seem to get passed the errors object, if any is generated?

**Comment by timothycrosley** [comment]
@ErwinHaasnoot, yes, that is intentional you can disable that behavior by setting a separate transformation function in case of error or None to do no special handling: `@hug.get(on_invalid=None)`
