### ISSUE TITLE
How do I catch/handle errors?

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#227]
Hi!

This seems like a feature that has not yet been properly documented. My API can in some situations throw custom exceptions, how do I let hug handle these errors gracefully, rather than ending up in a http 500 state?

Best,

Erwin

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

In hug 2.0.0 you can do the following:

    @hug.exception(Exception):
    def my_handler(exception):
         return {'my_exception': 'format'}

Where `Exception` can be replaced with the kind of exception you want to handle.
hug < 1.9.9 requires local exception handling (try, catch) within your handler.
Unfortunately, hug 2.0.0 features are not yet well documented but I hope to expand the documentation at time of release. Questions like this help me decide what areas need priority :)

Thanks!

~Timothy

**Comment by ErwinHaasnoot** [comment]
Cool, that waa pretty much what I was looking for. I'm currently running
the latest dev version, as I really need the Api Key handling. So will look
at it again on Monday!

Thanks so much!
