### ISSUE TITLE
How do I decorate hug decorators?

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#228]
Hi Tim,

Sorry, I'm opening a lot of issues here, but hopefully these can be integrated in the documentation at some point.

I'm looking to have a decorator that works similarly to hug.get, but has a few parameters set to certain variables already.

```
import hug
from functools import partial

my_get = partial(hug.get, requires=my_authentication)

@my_get('/')
def stuff():
    return 1
```
for example doesn't work, but I'm not quite clear why?

**Comment by timothycrosley** [comment]
Hi @ErwinHaasnoot,

I'm not sure quite why the partial doesn't work, but with hug 2.0.0 you never need to worry about using partial as all decorators are chainable. Which means you can get the equivalent of a partial just by not applying it to a function:

     import hug

    my_get = hug.get(requires=my_authentication)

    @my_get.urls('/')
    def stuff():
        return 1

Would be how you would implement the above with hug 2.0.0

Thanks!

~Timothy

**Comment by ErwinHaasnoot** [comment]
Ah really? It's that easy? Haha. Will try it out, thanks!
