### ISSUE TITLE
Include authentication methods in documentation

### ISSUE THREAD

**Issue by ErwinHaasnoot** [timothycrosley/hug#232]
Hi!

One thing that's still missing from the auto-generated docs, which are very good as is, is the possibility of including the methods of authentication required for using the different functions in the API. Ie, username,password verification, API key verification, which headers to use etc.

**Comment by timothycrosley** [comment]
Agreed, and this should be very simple to add, I'll make sure to get it in for the 2.0.0 release.

Thanks!

~Timothy
