### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by nicois** [timothycrosley/hug#234]
Looking at the (development branch) source, there is a method exposed via hug.API to register exception handlers. This looks like an idea method for integrating sentry to aggregate exceptions, as the middleware hooks don't seem to include exception references.

However, I see the following:

`TypeError: can't set attributes of built-in/extension type 'Exception'`

when trying this:
```python
hug.API.add_exception_handler(Exception, sentry, (None,))  
```

Am I missing something obvious? In any event, a couple of lines added to the readme would help others going down this route.

**Comment by timothycrosley** [comment]
Hi @nicois,

I've never used sentry before and looking through the docs here: https://docs.getsentry.com/hosted/clients/python/ it's not entirely clear how it should work, but I'd imagine it would look something like:

    from raven import Client

    client = Client('https://<key>:<secret>@app.getsentry.com/<project>')
    ...

    @hug.exception(Exception)
    def handle_exception(exception):
        client.captureException()

And I agree, this and several other new features need to get documented when 2.0.0 is released.

Thanks!

~Timothy

**Comment by nicois** [comment]
@timothycrosley, the syntax seems to work, but the handler is not fired: the 500 exception is bubbling up without the function being invoked.

For now I will make a simple decorator which I can wrap each API function with, but obviously it would be nicer to use the provided exception handler.

In case it helps, here's the top of a stack trace resulting in a 500 without the exception handler being invoked. Not that it matters, but the actual exception was _mssql.MSSQLDatabaseException.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "falcon/api.py", line 213, in falcon.api.API.__call__ (falcon/api.c:2583)
  File "falcon/api.py", line 182, in falcon.api.API.__call__ (falcon/api.c:2162)
  File "hug/interface.py", line 538, in hug.interface.HTTP.__call__ (hug/interface.c:14468)
  File "hug/interface.py", line 482, in hug.interface.HTTP.call_function (hug/interface.c:12905)
```

**Comment by nicois** [comment]
.. I should add that I am not (yet) using versioning. Is it possible that I need to pass a version number in for the handler to register correctly?
