### ISSUE TITLE
Comprehensive Documentation

### ISSUE THREAD

**Issue by Ubadub** [timothycrosley/hug#245]
Is there yet comprehensive documentation for this project? It seems very promising and I'll be following it to see where it goes but it would help to have a readthedocs (or similar) documentation of all the things HUG can do.

I am particularly interested because I want to contribute to the app (if at all possible) and it would help to have documentation of existing features on hand.

**Comment by timothycrosley** [comment]
Hi @Ubadub, 

I'm rapidly putting  more in-depth and complete documentation for hug here: http://www.hug.rest/website/learn you can edit the source of this documentation here: https://github.com/timothycrosley/hug/tree/develop/documentation

Thanks!

~Timothy
