### ISSUE TITLE
HTTP status codes

### ISSUE THREAD

**Issue by berdario** [timothycrosley/hug#246]
I wanted to report an error to the user (error 400) due to wrong arguments, but apparently hug can only return 200, 404 and 500 when there's an uncaught exception. (and maybe redirects?)

I had a brief look at the code, and it seems that this use case hasn't been thought for yet.

**Comment by timothycrosley** [comment]
HI berdario,
Thanks for reaching out! I'm not sure entirely what you mean? By default hug does return a 400 for wrong arguments, did you want to return some other error code? Furthermore, you can return any error code you want. Hug allows you to fully modify the response object in several areas. The most straight forward of which is:

    @hug.get()
    def my_argument(argument_1, argument_2, response= None):
          response.status = falcon.HTTP_400

 But, I'm afraid I'll need more information to fully address your question

Thanks!

~Timothy

**Comment by berdario** [comment]
I see, thank you.

I think that an example would be useful #247

**Comment by a523** [comment]
I fand  anthoer method :
```python
import hug
from falcon import HTTP_400, HTTPError

@hug.get()
def my_argument(argument_1, argument_2):
      raise HTTPError(HTTP_400)
```

I think this method has one advantage that it's not need add 'response' in the args.
so that, the business code separate from the interface code.
It,s not need send a 'response'  args for the my_argument function when i add cli interface(not http interface).

further on
```python
import hug
from falcon import HTTP_400, HTTPError

classs CustomError(HTTPError):
    def __init__(self):
        super().__init__(status=HTTP_400)

@hug.get()
def my_argument(argument_1, argument_2):
    raise CustomError()
```
