### ISSUE TITLE
Documentation doesn't output authenticator docstring

### ISSUE THREAD

**Issue by vortec** [timothycrosley/hug#252]
Hug version: develop branch

Following the example in ``examples/authentication.py``:

    authentication = hug.authentication.basic(hug.authentication.verify('User1', 'mypassword'))

And passing the authenticator into a function:

    @hug.get('/test', requires=authentication)

Results in ``null`` being outputted in the generated documentation:

    "/test": {
        "GET": {
            "inputs": {},
            "outputs": {
                "content_type": "application/json",
                "format": "JSON (Javascript Serialized Object Notation)"
            },
            "requires": [
                null
            ]
        }
    }

I expected it to show "Basic HTTP Authentication" as the docstring says.

This is because the ``@authenticator`` decorator applies the docstring to the wrapper function and not to the ``authenticate`` functions that is actually being executed.

**Comment by timothycrosley** [comment]
This is now fixed in the Develop branch, thanks for reporting :)
