### ISSUE TITLE
request parameter to def hidden by falcon.request.Request 

### ISSUE THREAD

**Issue by sadeveloper** [timothycrosley/hug#253]
I'm working with Ian implementing some API endpoints using hug. In general, it's been a great platform for productivity.

I have an unusual case where I am implementing an endpoint to consume JSON from Amazon in Amazon's format, so I don't have any control over the format. They send me `{ "version": "string",  "session": ... ,  "request": object }` which I am trying to map to a `def` in python with the signature `def dorequest(version, session, request)`. The issue is that a `request` is being mapped to my signature that's a `falcon.request.Request` object. What I'm trying to discover is how to access the JSON keys in the dictionary Amazon sends in some other way from within my `def`, or if there is some other workaround. Essentially, the Falcon `request` is hiding the JSON `request`. It's a collision where the Falcon `request` is being used, and the JSON key being hidden. I'm looking for a way to un-hide the `request` I want, even if it's just a workaround.

**Comment by timothycrosley** [comment]
Hi @sadeveloper,

I think the most direct way to resolve this issue would be to request the JSON body from your method instead of the individual arguments:

     @hug.get()
      def dorequest(body):
           pass # body here will equal { "version": "string",  "session": ... ,  "request": object }

Let me know if this resolves your issue :)

Thanks!

~Timothy

**Comment by ianthetechie** [comment]
That looks reasonable to me. Thanks for the quick response!

**Comment by sadeveloper** [comment]
Yes, thanks! I'm able to get the three keys out of the `body` object. That's a good workaround.
