### ISSUE TITLE
Fix website (for use on iPad)

### ISSUE THREAD

**Issue by mjmare** [timothycrosley/hug#273]
The hug website is unreadable on an iPad (Air 2). 
Menu items overlap text.
Textarea not responsive. 
White text overlaps white border. 
Minor and subjective: consider other colours. 

![img_0405](https://cloud.githubusercontent.com/assets/1711378/13905649/6e707186-eec6-11e5-9208-226e3cdab0a2.jpg)

**Comment by timothycrosley** [comment]
@mjmare, 

Thanks for reporting this! We will try to implement a fix for the ipad issues soon.
Where do you think other colors should be considered? And do you have suggestions?
I know on the main page lots of colors are used which can be overwhelming for some, but on the documentation pages I stuck with a relative safe and standard blue + gray color pattern.

Thanks!

~Timothy

**Comment by mjmare** [comment]
Hi Timothy

> On 20 Mar 2016, at 20:07, Timothy Edmund Crosley <notifications@github.com> wrote:
> 
> @mjmare <https://github.com/mjmare>,
> 
> Thanks for reporting this! We will try to implement a fix for the ipad issues soon.
> 
Great!
> Where do you think other colors should be considered? And do you have suggestions?
> I know on the main page lots of colors are used which can be overwhelming for some, but on the documentation pages I stuck with a relative safe and standard blue + gray color pattern.
> 
> 
It’s personal: the pages are colourful but they are a bit flat. Just not very attractive to me. 
I think (pure) white text on a grey background does not read very easily. 

About documentation. Have you thought of doing a video tutorial/walkthrough? 

Looking forward of learning more about Hug. 

Kind regards 

Marcel

**Comment by timothycrosley** [comment]
Hi @mjmare,

@BrandonHoffman has taken care of the mobile / iPad display issues and where discussing improvements to the color scheme of the site, stay tuned!

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
All right, we've now significantly simplified the color scheme :)

Thanks!

~Timothy

**Comment by mjmare** [comment]
Much much better. Thanks!

Marcel
