### ISSUE TITLE
Development runner: __hug__ is not defined

### ISSUE THREAD

**Issue by vortec** [timothycrosley/hug#274]
On the current ``develop`` branch, running ``hug -f app.py`` does not inject the ``__hug__`` module into the runtime.

**Comment by timothycrosley** [comment]
@vortec,

Can you provide the example code being tested against? To be more specific: `hug -f app.py` is not what creates the `__hug__` variable, but instead the first decorator does. So if you try to access `__hug__` before you've assigned any decorators it wont exist.

Works:

     import hug
     

     @hug.get()
     def endpoint():
          pass

     __hug__.http.add_middleware(x) # SUCCESS: __hug__ will exist because @hug.get created it


Does not work:

     import hug
     
     __hug__.http.add_middleware(x) # FAILURE: nothing ever created __hug__


     @hug.get()
     def endpoint():
          pass

     
To solve this hug 2.0.0 introduces a safe way to access the API that will also create the singleton if it doesn't yet exist: `hug.API(__name__).http.add_midleware(x)` should work no matter when it's called.

Let me know if this resolves this issue.

Thanks!

~Timothy

**Comment by vortec** [comment]
Yes, that works. I wanted to initialize the middleware before did that before the first decorator was executed. Thanks!
