### ISSUE TITLE
output format based on Accept request header

### ISSUE THREAD

**Issue by Toilal** [timothycrosley/hug#277]
Is there anything in hug to support hot defining of output format based on the value of [Accept request header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) ?

I wish I could implement some API that speak XML and JSON, and clients could use either based on the value of this header.

**Comment by timothycrosley** [comment]
Hi @Toilal,

Thanks for letting us know of this use case. @BrandonHoffman is totally correct that there are existing ways to do this using other headers / approaches, and that you can do implement this for your API. I also totally agree that this would be a useful addition to the core API and will be working on adding it, unless you had an intention of submitting a pull request that adds it and becoming a contributor?

Thanks!

~Timothy Crosley

**Comment by Toilal** [comment]
I would work on a pull request, no problem, but in about 10 days because
i'm currently too busy.

Thanks for all the work and clear communication ☺️

**Comment by timothycrosley** [comment]
@Toilal,

I've implemented support for this here: https://github.com/timothycrosley/hug/pull/298/files so that it could be ready for 2.1.0 release, thanks for recommending this useful feature!

~Timothy
