### ISSUE TITLE
Validator expects `args` in input_parameters

### ISSUE THREAD

**Issue by lseelenbinder** [timothycrosley/hug#280]
At https://github.com/timothycrosley/hug/blob/develop/hug/interface.py#L161 requests are falling (400 response code) because of a failed validation. After inserting a print on line 161 of `print(require, input_parameters)`, I got this on stdout:

`args {'paramA': 'foo', 'paramB': 'bar'}`

So it looks like it is searching for `args` in `input_parameters`. 

This could be caused because I am using a decorator (using `functools.wraps` correctly) that accepts `*args, **kwargs`, but I am not certain. Otherwise, there is no parameter `args` for the function.

Any ideas?

Thanks!
Luke

**Comment by timothycrosley** [comment]
Hi @lseelenbinder,

I think to resolve your issue you can just replace your usage of `functools.wraps` with `hug.wraps`. While `functools.wraps` does pass along a lot of information, it still doesn't provide the full function spec of the original which is needed for hug to be able to correctly introspect.

Thanks!

~Timothy

**Comment by lseelenbinder** [comment]
Hey @timothycrosley,

I updated the code to use `hug.wraps` and the `args` error went away; however, it looks like I'm still missing some piece.

I have a decorator that updates an argument named `db`, like:

```
def uses_db(func):
    """Decorator that creates a database connection and passes it to the wrapped function"""
    @hug.wraps(func)
    def func_wrapper(*args, **kwargs):
        config = configparser.ConfigParser()
        config.read('config.ini')

        db_config = config['db']
        host = db_config['host']
        user = db_config['user']
        password = db_config['password']

        db = db_helpers.DatabaseWrapper(host, user, password)
        return func(db, *args, **kwargs)
    return func_wrapper
```

And I use it like this:

```
@hug.get('/endpoint', versions=1, requires=auth)
@decorators.uses_db
def endpoint(db: db_helpers.DatabaseWrapper, id: str, user: hug.directives.user):
     obj = db.get_obj(id=id)[0]
     return obj
```

Unfortunately, it's returning a `400` error saying the `db` parameter is not supplied. This worked previously.

Thanks!

Luke

**Comment by timothycrosley** [comment]
Hi @lseelenbinder,

I think there are a few competing concepts here, you can't get the db object from the db_helpers.DatabaseWrapper directive, because it's the hug.get decorator that actually expends it into a variable. Here's what I would do:

I would move the connection logic to a middleware, that adds the db to request.context, then the db_helper directive could read that object.

Is this helpful?

Thanks!

~Timothy

**Comment by lseelenbinder** [comment]
Thank you! The middleware method works well.
