### ISSUE TITLE
Error handling whole API service instead of each api endpoint

### ISSUE THREAD

**Issue by khanhicetea** [timothycrosley/hug#287]
Hi,

`hug` is cool library for make a RESTful service. So I decided make a framework based on it. This is my repo : https://github.com/khanhicetea/hug-n-rest

But I'm stuck with how can I handle exceptions in whole API service.

Example:

When I raise HTTPNotFound exception in [service class](https://github.com/khanhicetea/hug-n-rest/blob/master/app/services/base.py#L31), I added the exception handler in `app/__init__.py` like this

```python
from .hug_and_rest import current_app


def init_app_callback():
    import hug

    @hug.extend_api()
    def register_blueprint():
        from . import api
        return [api]

    @hug.exception(Exception)
    def exception_handler(exception):
        print(exception)

current_app.init_app(init_app_callback)
```

And I got the empty response body, no print out

```
HTTP/1.1 404 Not Found
Connection: close
Date: Mon, 04 Apr 2016 17:23:52 GMT
Server: gunicorn/19.4.5
content-length: 0
content-type: application/json


```

**Comment by khanhicetea** [comment]
I find out all `HTTPNotFound` exceptions will be catch by `HTTPInterfaceAPI.base_404` (https://github.com/timothycrosley/hug/blob/develop/hug/api.py#L222)

So good if we could override that handler :smiley:

**Comment by timothycrosley** [comment]
Hi @khanhicetea,

You can indeed override the base 404 handler cleanly :), as shown here:

https://github.com/timothycrosley/hug/blob/develop/examples/override_404.py

The exception handling is intentionally only for things that happen during request handling (not init), as things outside of that should just be handled by a try: except: locally, which is fairly easy to do, and would only need to be done once.

Hope this is helpful,

Thanks!

~Timothy
