### ISSUE TITLE
Add benchmarks to repo and ensure performance regressions don't occur

### ISSUE THREAD

**Issue by rodcloutier** [timothycrosley/hug#293]
I was wondering if we had tried to quantify the cost of using Hug.
To my surprise, there seems to be a 40% performance drop (23297 from 35911 request/second)  when using hug in a simple hello world scenario.

Is there a plan to profile and explain the performance drop?

## Scenarios

Python 3.5.1

###  Falcon 0.3.0
```
import falcon

class ThingsResource(object):
    def on_get(self, req, resp):
        resp.status = falcon.HTTP_200  # This is the default status
        resp.body = 'Hello World !'

app = falcon.API()
things = ThingsResource()
app.add_route('/', things)
```
###  Hug develop branch @f916f4943e801bf85c6cfdeb153b4483f28c2426
```
import hug

@hug.get('/')
def hello():
    return "hello world"
```

## Server

Served with `gunicorn`and using the `meinheld`worker

`gunicorn <falcon_test:app | hello:__hug_wsgi__> --workers=2 --worker-class=meinheld.gmeinheld.MeinheldWorker`

## Benchmark

Running `wrk`with the following options:

`wrk -t10 -c200 -d30s http://127.0.0.1:8000/`

###  Falcon

```
Running 30s test @ http://127.0.0.1:8000/
  10 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.56ms  820.43us  30.78ms   93.29%
    Req/Sec     3.61k   293.58     7.09k    92.01%
  1081057 requests in 30.10s, 189.70MB read
  Socket errors: connect 0, read 56, write 0, timeout 0
Requests/sec:  35911.67
Transfer/sec:      6.30MB
````

### Hug

```
Running 30s test @ http://127.0.0.1:8000/
  10 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.58ms  842.25us  64.73ms   96.27%
    Req/Sec     2.34k    90.01     3.78k    89.50%
  699435 requests in 30.02s, 112.73MB read
  Socket errors: connect 0, read 61, write 0, timeout 0
Requests/sec:  23297.93
Transfer/sec:      3.75MB
```

**Comment by vortec** [comment]
I'm pretty impressed by the speed gain meinheld provides.

My test results:

## Falcon
```
Running 30s test @ http://127.0.0.1:8000/
  10 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.28ms    4.06ms  87.17ms   95.86%
    Req/Sec     2.88k   599.14     3.73k    77.53%
  860060 requests in 30.04s, 150.92MB read
  Socket errors: connect 0, read 54, write 0, timeout 0
Requests/sec:  28631.16
Transfer/sec:      5.02MB
```

## Hug
```
Running 30s test @ http://127.0.0.1:8000/
  10 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.61ms    3.76ms  97.02ms   96.99%
    Req/Sec     2.14k   290.98     2.37k    92.83%
  640232 requests in 30.03s, 103.19MB read
  Socket errors: connect 0, read 61, write 0, timeout 0
Requests/sec:  21322.90
Transfer/sec:      3.44MB
```

**Comment by timothycrosley** [comment]
@rodcloutier, there has been some work here: http://pycnic.nullism.com/images/pycnic-bench.png and I'm working to create benchmarks to the repo and to the test suite to ensure performance regressions don't happen. However, I can say very confidently that 1:1 hug performs no where near 40% slower then Falcon, but instead around 5-10% at worst case. As one of many examples of where your test is not a 1:1, your using costly json output for hug but simple no processing text output for falcon. This probably alone explains the benchmarking difference.

**Comment by timothycrosley** [comment]
@rodcloutier I've added benchmarks here: https://github.com/timothycrosley/hug/tree/develop/benchmarks/http that provide a 1:1 comparison feel free to update them to add additional frameworks or use cases, currently the tests show a very small and expected performance difference then writing Falcon by hand.
