### ISSUE TITLE
HTTPUnauthorized with Falcon 1.0.0rc1

### ISSUE THREAD

**Issue by revictus** [timothycrosley/hug#295]
Currently with Falcon 1.0.0rc1 anytime HTTPUnathorized is raised (like in authentication) it throws a TypeError due a missing 'challenges' argument.

`TypeError: __init__() missing 1 required positional argument: 'challenges'
`

In Falcon 1.0.0rc1 there is challenges argument that is now necessary when raising HTTPUnauthorized that was not present in Falcon 0.3.0:

`
exception falcon.HTTPUnauthorized(title, description, challenges, **kwargs)`

[http://falcon.readthedocs.org/en/latest/_modules/falcon/errors.html#HTTPUnauthorized]

**Comment by timothycrosley** [comment]
Hi @revictus, thanks for reporting! This is valuable to know before we release hug 2.1.0 which will coincide with the Falcon 1.0.0 release. I'll work on a fix for this momentarily

**Comment by timothycrosley** [comment]
This has been fixed here: https://github.com/timothycrosley/hug/pull/296/files. Thanks again for reporting!
