### ISSUE TITLE
Allow for content-length 0 when request is in JSON format

### ISSUE THREAD

**Issue by curiousily** [timothycrosley/hug#300]
Currently, to skip the parsing of the body it is required the content length to be None. Reference [here](https://github.com/timothycrosley/hug/blob/develop/hug/interface.py#L445).

If the content-length is 0 and content-type is 'application/json' the following error occurs

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Is it ok to parse only if content-length != None and content-length > 0 ?

**Comment by timothycrosley** [comment]
@curiousily I think this would be a reasonable improvement, and would be a good addition for the 2.1.0 release. Thanks for reporting!

~Timothy

**Comment by timothycrosley** [comment]
Hi @curiousily,

Closing this issue as a fix is now merged in develop, fully tested, and ready for the next release.

Thanks!

~Timothy

**Comment by curiousily** [comment]
Hey @timothycrosley,

Will test it out when 2.2.0 is released.

Thank you!

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
