### ISSUE TITLE
Python Exception Thrown When Using Endpoint Versioning and Hitting Non-Versioned URL

### ISSUE THREAD

**Issue by dreadwestern** [timothycrosley/hug#304]
I am following the versioning example in the Hug API documentation, and am seeing a Python exception thrown when hitting non-versioned URLs (i.e. the URLs for generating API documentation).

These URLs work as advertised:
http://localhost:8000/v1/echo?text=foo
http://localhost:8000/v2/echo?text=foo

These URLs fail every time and generate the exception:
http://localhost:8000
http://localhost:8000/documentation

Below is the Hug server error log from my request:

    Serving on port 8000...
    127.0.0.1 - - [06/May/2016 10:27:40] "GET /v1/echo?text=foo HTTP/1.1" 200 5
    127.0.0.1 - - [06/May/2016 10:27:44] "GET /v2/echo?text=foo HTTP/1.1" 200 11
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
     File "/Users/nick/.virtualenvs/api-test-project/lib/python3.5/site-packages/falcon/api.py", line 182, in __call__ responder(req, resp, **params)
      File "/Users/nick/.virtualenvs/api-test-project/lib/python3.5/site-packages/hug/api.py", line 266, in handle_404 to_return['documentation'] = self.documentation(url_prefix, self.determine_version(request, False))
    File "/Users/nick/.virtualenvs/api-test-project/lib/python3.5/site-packages/hug/api.py", line 184, in documentation versions_list.remove(None)
    ValueError: list.remove(x): x not in list
    127.0.0.1 - - [06/May/2016 10:27:47] "GET / HTTP/1.1" 500 59

**Comment by dreadwestern** [comment]
Here is the code example being run:

    # filename: versioning_example.py
    """A simple example of a hug API call with versioning"""
    import hug

    @hug.get('/echo', versions=1)
    def echo(text):
        return text


    @hug.get('/echo', versions=range(2, 5))
    def echo(text):
        return "Echo: {text}".format(**locals())

**Comment by timothycrosley** [comment]
Hi @dreadwestern,

Thanks for reporting! This issue is known and it is fixed in the current development branch (which you can install using `pip install git+git://github.com/timothycrosley/hug@develop` to verify) we are waiting on Falcon to finish releasing 1.0.0 before we push this new version, they are on their second release candidate with the final 1.0.0 release coming any day now, which will coincide with a hug 2.1.0 release containing this fix.

Thanks!

~Timothy

**Comment by dreadwestern** [comment]
Thanks Timothy, that's great news. In the meantime, I will just work around it. 

Cheers, Nick

**Comment by dreadwestern** [comment]
@timothycrosley 

Fix was verified in the dev branch. Thanks again!

**Comment by timothycrosley** [comment]
Closing this issue as the dev branch has now been pushed to PYPI

Thanks!

~Timothy
