### ISSUE TITLE
How could I share object in multiple files 

### ISSUE THREAD

**Issue by erhuabushuo** [timothycrosley/hug#305]
How could I share objects in multiple files.

**Comment by erhuabushuo** [comment]
for example: hug.config

**Comment by erhuabushuo** [comment]
If I split APIs over multiple files, and I want to share config object.

**Comment by timothycrosley** [comment]
@erhuabushuo I'm not sure I fully understand: If you simply want to share a config object than this is purely a Python problem, and one that is easily solved:

- config.py
- module1 - imports config.py
- module2 - imports config.py

Is there something beyond this you would like to accomplish? Any more details you can provide?

Thanks!

~Timothy
