### ISSUE TITLE
Is Hug supported by any cloud platform?

### ISSUE THREAD

**Issue by fbukevin** [timothycrosley/hug#308]
I really love the concise and simple way of Hug. I've used Hug on my local server. Now I want to use Hug as a public API server and deploy it to any cloud platform such as heroku, GAE, Azure and so on. But I hardly can find support or tutorial.  I'm looking for help!

Is there any platform supporting Hug? Or I should integrate Hug into exist web framework such as Flask, Django, bottle...?

Thanks!

**Comment by cag** [comment]
You should be able to use hug directly on heroku at least. Just follow the instructions on using heroku with python. When you get to the part about the Procfile, use a wsgi capable server like gunicorn and pass it your hug wsgi interface.

I don't have any experience with the others. Ultimately, it may be worthwhile to learn how to set up a server. Best of luck!

**Comment by fbukevin** [comment]
@cag Hi, thanks! And I found that Hug need to use `hug -f app.py` to launch server. How do I make that happen?

**Comment by timothycrosley** [comment]
Hi @fbukevin, you do not need to use hug -f app.py to start a hug app, instead you can use any standard WSGI speaking server (like uwsgi or gunicorn) to run it. You can see this documented at the bottom of the getting started guide: http://www.hug.rest/website/quickstart. In general you can look at any guide that explains how to get Flask or similar up and running on said cloud platform and replace `app` with `__hug_wsgi__`

Hope this helps!

~Timothy

**Comment by seanfcarroll** [comment]
Perhaps useful: https://github.com/BFriedland/heroku-hug-demo
