### ISSUE TITLE
Exception handling issue with extend_api

### ISSUE THREAD

**Issue by soloman1124** [timothycrosley/hug#309]
Hi, I would like to set a global exception handler using `hug`, however, I am encountering the following issue. Hope if you can provide me some insight or help :) (I am currently using version `2.0.6`)

My project structure is like this:

```
[project]
--> `__init__.py`
--> [api]
----> `task.py`
```

in the `project/__init__.py` I have something like:

``` python
# project/__init__.py
import hug

from project.api import task

@hug.exception()
def handle_exception(exception):
    return {'error': "Python broke again! Don't blame us!"}

@hug.get('/project')
def hello():
    raise Exception('task')

@hug.extend_api('/tasks')
def task_api():
    return [task]
```

in the `project/api/task.py` I have something like:

``` python
# project/api/task.py

import hug

@hug.get('/')
def say_hi():
    raise Exception('task')
```

The issue is that:

`GET /project` would correctly invokes the exception handler, however, `GET /tasks` does not. 

I also tried to add another exception handler in  `project/api/task.py`, e.g.

``` python
# project/api/task.py

import hug

@hug.exception()
def handle_exception(exception):
    return {'error': "TEST!!!"}

@hug.get('/')
def say_hi():
    raise Exception('task')
```

However, the behaviour now is that exceptions from all of my routes are now handled with the latest handler, and the old one is completely ignored. 

Thanks a lot!

**Comment by timothycrosley** [comment]
Closing this as your patch has been pushed in the latest release, thanks!
