### ISSUE TITLE
reload if file was changed / disable 404 documentation

### ISSUE THREAD

**Issue by ghost** [timothycrosley/hug#31]
Hug is great! May I suggest adding:

- reload if file was changed (like flask)
- setting to disable the 404 documentation

**Comment by timothycrosley** [comment]
HI @fvea,

I think those are both great ideas! And will make sure to implement them before the next release.
There is currently a way to disable 404 documentation, but it should be more clear and not require creating a custom server.py file:

    import my_hug_api
    import hug


    wsgi_api = hug.run.server(my_hug_api, sink=None)

I'll try to add a flag that can be passed to the hug command, as well as think of a way to cleanly disable it in code.

Thanks!

Timothy

**Comment by timothycrosley** [comment]
Fixed in 1.1.0
