### ISSUE TITLE
CLI arguments: default values always used

### ISSUE THREAD

**Issue by mhavel** [timothycrosley/hug#320]
I'm currently having troubles with `hug` v2.1.2 and the `cli` routing.

Just take your example `first_step_3.py', and add eg. a default value to age:

```python
@hug.cli()
def happy_birthday(name: hug.types.text, age: hug.types.number=23):
    # things here
    pass
```

If you now run `hug -f first_step_3.py matt 10`, this will use the age of 23.

Am I doing anything wrong? I'm completely new to `hug`, and despite the fact I like what I see, the doc is still very poor ;) but this is already an opened issue.

Anyway great piece of software.

**Comment by timothycrosley** [comment]
Hi @mhavel,

The correct command should be `hug -f first_step_3.py -c happy_birthday matt 10` when I run this I correctly get an age of 10. Let me know if you still run into issues running it in this manor.

Glad you like hug!

Thanks!

~Timothy

**Comment by mhavel** [comment]
Thx @timothycrosley, but unfortunately this still does not work. I had a typo in my original message and was indeed typing the `-c happy_birthday` part.

Here is my full source:

```python
import hug

@hug.cli()
def happy_birthday(name: hug.types.text, age: hug.types.number=23):
    """Says happy birthday to a user"""
    return dict(name=name, age=age)
```

my command:

```bash
hug -f hug0.py -c happy_birthday matt 10
```

and my output:

```ascii
{'age': 23, 'name': 'matt'}
```

Am I running crazy? (very possible :))

**Comment by timothycrosley** [comment]
Not crazy at all! When you add a default it essentially switches to a forced named parameter (under the hood it's using ArgParse so it has to follow all it's usage patterns) so to call it you would then do:

`hug -f hug0.py -c happy_birthday matt --age 10`

I hope this makes sense! Thanks!

~Timothy

**Comment by mhavel** [comment]
it does indeed! Thanks, and sorry for the confusion.
