### ISSUE TITLE
CLI: support for class object

### ISSUE THREAD

**Issue by mhavel** [timothycrosley/hug#322]
Another thing I noticed about the CLI routing: it does not work on class methods like `get`.

What'd be great, would be something like:

```python
class MyClass:
    @hug.object.cli()
    def mymethod(self):
        return 'cool'
```

**Comment by timothycrosley** [comment]
Agreed! I'll work on implementing this for the next version.

**Comment by timothycrosley** [comment]
Implemented here, in develop, and ready for the next release:

https://github.com/timothycrosley/hug/pull/378/files

usage:

```python
@hug.object
class MyClass:
    @hug.object.cli
    def mymethod(self):
        return 'cool'
```

Thanks!

~Timothy

**Comment by mhavel** [comment]
Awesome, thanks!

Mathieu

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
