### ISSUE TITLE
API directive doesn't play nice with extend_api

### ISSUE THREAD

**Issue by ariscn** [timothycrosley/hug#323]
Expected: Endpoint receives the calling API.
Actual: Endpoint always receives the API passed at declaration.

**Comment by timothycrosley** [comment]
Hi @ariscn,

Thanks for reporting!

This will be fixed alongside the reported issues with extend_api slated for the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
This has been verified as fixed here: https://github.com/timothycrosley/hug/pull/375/files and will be ready for the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
