### ISSUE TITLE
Multipart Request Issue

### ISSUE THREAD

**Issue by thatGuy0923** [timothycrosley/hug#329]
Hello, I am attempting to send a multipart/form-data request to a hug endpoint, however the file I am sending with the name image is not found therefore raising a 400 Bad Request exception. I am using python version 3.5.1

This is the route I am sending the multipart/form-data request:
``` python
@hug.post('/user/upload_photo', requires=token_key_authentication)
def upload_photo(user: hug.directives.user, image):
        #s3 upload code here
```
I am sending the request with PAW,
The request body I am sending looks like this:
```
POST /user/upload_photo HTTP/1.1
Authorization: KKbdeLa5pqaBNdu4j1AgrbhAY
Content-Type: multipart/form-data; boundary=__X_PAW_BOUNDARY__
Host: 192.168.99.100:8000
Connection: close
User-Agent: Paw/2.3.3 (Macintosh; OS X/10.11.6) GCDHTTPRequest
Content-Length: 13839

--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="image"; filename="294705_10201235674960027_1869713460_n.jpg"
Content-Type: image/jpeg
```

I believe the request is dying on cgi's parse_multipart which is returning an empty string, here in
input_format.py:
https://github.com/timothycrosley/hug/blob/develop/hug/input_format.py#L77

**Comment by thatGuy0923** [comment]
I added a log statement in the decerator here:
```python
@content_type('multipart/form-data')
def multipart(body, **header_params):
    """Converts multipart form data into native Python objects"""
    print('HITTING DECTORATOR')
    if header_params and 'boundary' in header_params:
        if type(header_params['boundary']) is str:
            print('IS STRING')
            print(header_params)
            header_params['boundary'] = header_params['boundary'].encode()
    print(body)
    form = parse_multipart(body, header_params)
    print(form)
    for key, value in form.items():
        if type(value) is list and len(value) is 1:
            form[key] = value[0]
    return form
```

This was the log:
```
HITTING DECTORATOR
IS STRING
{'boundary': '__X_PAW_BOUNDARY__', 'charset': 'utf-8'}
<falcon.request_helpers.Body object at 0x105a65358>
{} 
```

As you can see, when I print the form data after the parse_multipart function is called, nothing is returned. Hug is detecting that I am sending a multipart request, but something in cgi's parse_multipart is not finding the image in the body.

**Comment by thatGuy0923** [comment]
It looks like instead of using parse_multipart, cgi's FieldStorage implementation seems to be the way other falcon-middleware implements multipart requests. 

It looks like this issue has been addressed by falcon and they recommend using cgi FieldStorage as seen here https://github.com/falconry/falcon/issues/469 

There is a middleware that uses FieldStorage as well and is implemented here https://github.com/yohanboniface/falcon-multipart

**Comment by thatGuy0923** [comment]
So in exploring the issue, I realized the stream object is in the body object passed into the multipart request. I made a modification to the multipart request, because cgi's parse_multipart requires a stream object, I passed the stream object of body into the request and there were no errors.

This is the change I made:
```python
form = parse_multipart(body.stream, header_params)
```
By passing the stream object this is the dict of the retuned form:

**Comment by cag** [comment]
@thatGuy0923 Whoa nice. When I get a chance, I'll look into this as well. I originally wanted to use multipart with FieldStorage, so your finding a way that works is totally rad.

**Comment by thatGuy0923** [comment]
@timothycrosley Do you have any input on this?

**Comment by timothycrosley** [comment]
@thatGuy0923 great work on this! Sorry I didn't get back sooner, I think your fix was the correct current term solution till we implement a more robust solution in the future (preferably, Falcon will add support for this as @cag mentioned - if they don't we can do it in a 3.0.0 release)

Your fix is now in development and will be pushed with the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
