### ISSUE TITLE
Example for extend_api decorator

### ISSUE THREAD

**Issue by sloat** [timothycrosley/hug#33]
I whipped up a quick example from looking through the decorators.py source:

`__init__.py`

    import hug
    from . import something

    @hug.get('/')
    def say_hi():
        return "Hi from root"

    @hug.extend_api('/something')
    def something_api():
        return [something]
    
    #alternatively
    __hug__.extend(something, '/something')

`something.py`

    import hug

    @hug.get('/')
    def say_hi():
        return 'hello from something'

**Comment by timothycrosley** [comment]
Thanks! This is awesome, I'll add it to the Readme :)
