### ISSUE TITLE
Using HTTPie, sending a POST, PUT, or DELETE request without payload raises a TypeError

### ISSUE THREAD

**Issue by PrashntS** [timothycrosley/hug#330]
Hey there!

Making a request from `httpie` as `http delete localhost:8900/api/entity/1`, raises a `TypeError` on this definition:

```python
@hug.delete('/{uid}')
def delete_entity(uid: hug.types.text):
  try:
    item = Entity.get(Entity.id == uid)
  except peewee.DoesNotExist:
    raise falcon.HTTPNotFound
  else:
    item.delete_instance()
    return item.repr
```

The traceback (truncated):

```
[2016-06-05 13:50:14 +0530] [41014] [ERROR] Error handling request /api/entity/1
Traceback (most recent call last):
  ::

  File "/Users/prashantsinha/.virtualenvs/BioDB/lib/python3.5/site-packages/hug/api.py", line 381, in api_auto_instantiate
    return module.__hug_wsgi__(*kargs, **kwargs)
  File "falcon/api.py", line 215, in falcon.api.API.__call__ (falcon/api.c:2563)
  File "falcon/api.py", line 189, in falcon.api.API.__call__ (falcon/api.c:2182)
  File "/Users/prashantsinha/.virtualenvs/BioDB/lib/python3.5/site-packages/hug/interface.py", line 581, in __call__
    input_parameters = self.gather_parameters(request, response, api_version, **kwargs)
  File "/Users/prashantsinha/.virtualenvs/BioDB/lib/python3.5/site-packages/hug/interface.py", line 447, in gather_parameters
    content_type, content_params = parse_content_type(request.content_type)
  File "/Users/prashantsinha/.virtualenvs/BioDB/lib/python3.5/site-packages/hug/format.py", line 35, in parse_content_type
    if ';' in content_type:
TypeError: argument of type 'NoneType' is not iterable
```

Funny though, if I add some random parameter in HTTPie request, it works fine. eg: `http delete localhost:8900/api/entity/1 _=__`

I would open a Pull Request with the fix, however, **I am not sure if it is something that I am doing wrong here**. 😕 

A trivial patch for the fix can be:
```python
def parse_content_type(content_type):
    """Separates out the parameters from the content_type and returns both in a tuple (content_type, parameters)"""
    if content_type is not None and ';' in content_type:
        return parse_header(content_type)
    return (content_type, empty.dict)
```
in `hug/format.py`

Thanks!

**Comment by vortec** [comment]
Which version do you use?

**Comment by PrashntS** [comment]
I have the version `0.9.3` from `homebrew` at the moment.
I think it's not a problem with `hug`, as such. I read `httpie` docs and found that `-f` parameter sets the `content-type` headers.

However, this certainly shouldn't raise a `TypeError` which leads to `500` error -- rather, the client should be sent a `400 Bad Request` with a `Missing Header` description.

**Comment by timothycrosley** [comment]
@PrashntS Thanks for finding and fixing this issue! Good work! Your fix has been merged into develop and will make its way into the next release

**Comment by timothycrosley** [comment]
2.2.0 has now been officially pushed to PYPI with this issue resolved

Thanks!

~Timothy
