### ISSUE TITLE
Logging additions

### ISSUE THREAD

**Issue by gsquire** [timothycrosley/hug#333]
The logging middleware is lacking things like current time, response size, or client IP. Would you be interested in adding these into something like [nginx's combined format](http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format)?

I'd be happy to submit a PR.

**Comment by timothycrosley** [comment]
@gsquire, yes I think this would be very useful! If you're still interested in putting together a PR I would be happy to review it

**Comment by gsquire** [comment]
Sure, I can do that.
