### ISSUE TITLE
Custom 404 Handlers Are Ignored When Using @hug.extend_api Decorator

### ISSUE THREAD

**Issue by dreadwestern** [timothycrosley/hug#334]
Steps to reproduce:
1. Create a root Hug resource with a custom not_found handler defined with the @hug.not_found decorator.
2. Create a separate resource that is loaded using @hug.extend_api
3. Raise a falcon.HTTPNotFound error from within one of the GET routes defined in the child resource.

Behavior:
Hug intercepts the 404 error and returns the correct HTTP status "404 Not Found" in the response, but the output is truncated to 0 bytes.

Desired behavior:
Hug routes the 404 error to the custom not_found handler and outputs the custom response, along with the correct HTTP status. Basically, have it behave the same way it does for all falcon.HTTPNotFound errors raised in the root resource.

My test setup is below:

```
# test_custom_404.py
import hug
import falcon

from app import extends

@hug.extend_api()
def load_resources():
    return [extends]

@hug.get('/hello')
def hello():
    return {'module': 'root', 'message': 'hello world'}

@hug.get('/hello-gone')
def hello_gone():
    raise falcon.HTTPNotFound()

@hug.not_found()
def not_found():
    return {'error': {
                'status': falcon.status.HTTP_NOT_FOUND,
                'description': 'URL is invalid.'
            }}


# extends.py
import hug
import falcon

@hug.get('/extends/hello')
def hello():
    return {'module': 'extends', 'message': 'hello world'}

@hug.get('/extends/hello-gone')
def hello_gone():
    raise falcon.HTTPNotFound()

```

**Comment by incognick** [comment]
I think #374 fixed this.

**Comment by timothycrosley** [comment]
@incognick that's correct. Going ahead and closing this issue. Thanks!
