### ISSUE TITLE
Middleware based on generators 

### ISSUE THREAD

**Issue by leiserfg** [timothycrosley/hug#335]
Some middlewares work both on request and responses. hug should allow to declare them in that way:

``` py
@hug.middleware()
def mid(request):
    print('the request comes')
    response, resource = yield request
    print('the response goes')
    yield response
```

**Comment by leiserfg** [comment]
@timothycrosley I did the pull request to fix it, may I re-send it to be acepted for hacktoberfest?

**Comment by timothycrosley** [comment]
Thanks for implementing this! The pull request is now complete and in development branch so I'm closing this branch, I hope you were able to get your hacktoberfast commit from it,

Thanks!

~Timothy
