### ISSUE TITLE
QuickStart Final step Production HTTP use - Apache mod_wsgi

### ISSUE THREAD

**Issue by sevillalarry** [timothycrosley/hug#339]
Hi,

I'm new to Hug.

In your QuickStart, you gave example on uwsgi and Gunicorn.

Is there a way to use it on Apache w/ mod_wsgi?

**Comment by cag** [comment]
Yes. Assuming your module is available to your default python, just make a
wsgi file with `from your_module import __hug_wsgi__ as application`, and
that is the file you give mod_wsgi in that one directive.

**Comment by leonel-lordford** [comment]
HI, I'm really new to hug and python, can you point me to some doc to get this done? I mean, how can I expose my hug main script (I'm using routes and different modules...) via Apache?
thanks for this amazing work...
