### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by felipevolpone** [timothycrosley/hug#34]
Hey, great work! 
Do you have plans for future features? I would like to help the project. Maybe you could create issues tagged as bugs or enhancements.

**Comment by timothycrosley** [comment]
Hi @felipevolpone, I definitely have a bunch of plans for enhancements as time goes on, I think adding them all as issues so others can contribute is a great idea! I'll close this issue once I've put in a collection of them tonight.

Thanks!

~Timothy

**Comment by Mec-iS** [comment]
Hi guys,
I had the same idea, the first thing that came to my mind was to add support for [HYDRA framework](http://www.w3.org/ns/hydra/spec/latest/core/). "Hydra is a lightweight vocabulary to create hypermedia-driven Web APIs.", it makes APIs self-descriptive and allows navigation by [smart-clients](http://www.markus-lanthaler.com/hydra/console/?url=http://www.markus-lanthaler.com/hydra/event-api/)
Cheers!

**Comment by timothycrosley** [comment]
Closing this as I've added a few issues and will be adding more as I think of them :) Always open to more suggestions and improvments as well.

Thanks!

~Timothy
