### ISSUE TITLE
Route with argument on root clobbers documentation route

### ISSUE THREAD

**Issue by jmmills** [timothycrosley/hug#342]
Example:
```python
import hug

@hug.route('/{thing}')
def get_thing(thing):
    return 'Thing'
```

Will trigger when asking for root with no argument, perhaps I'm not understanding a deeper feature here?

**Comment by prashnts** [comment]
I believe you need a default value here if you want root without argument.

Perhaps:
```python
@hug.route('/{thing}')
def get_thing(thing=None):
    return 'Thing'
```

**Comment by jmmills** [comment]
@prashnts nope, none-ing it doesn't do the trick. This might be a bug in the route handler?

**Comment by jmmills** [comment]
Okay, I figured it out... just throw  not found exception:

```
@hug.route('/')
def root():
    raise falcon.HTTPNotFound

@hug.get('/{thing}')
def get_thing(thing):
    return thing
```

Is this worth putting in an example?

**Comment by timothycrosley** [comment]
@jmmills yes I think it is! I'll add one soon
