### ISSUE TITLE
hug.test does not pass along query parameters if the endpoint isn't expecting them.

### ISSUE THREAD

**Issue by owattenmaker** [timothycrosley/hug#348]
Say I have an endpoint:

``` py

import hug
@hug.urls.get('/foo') # or whatever this syntax is 
def bar(request, response):
    return request.params
```

Then in my testing suit I have:

``` py
import hug
def test_foo():
    hug.test.get('/foo', {'hello': 'world'})
```

I have noticed that the `requests.params` dict will not be populated with what I gave it. `request.params` will be an empty dict.

Is this the intended behavior? The reason I ask is because as far as I've seen you can't just add the parameters to the endpoint specified. It will result in a 404 error.

**Comment by timothycrosley** [comment]
After some investigation I've determined this was just a bug in how you are calling the testing API, for the correct signature see the tests I've added here: https://github.com/timothycrosley/hug/pull/476/files

Essentially you need to change your test to read:

```python
import hug
import api_module


def test_foo():
    hug.test.get(api_module, '/foo', params={'hello': 'world'})
```

And then you will achieve the desired result.

**Comment by bachya** [comment]
@timothycrosley: This isn't what's represented on [the front page of this repo](https://github.com/timothycrosley/hug#testing-hug-apis):

```
hug.test.get(happy_birthday, 'happy_birthday', {'name': 'Timothy', 'age': 25}) # Returns a Response object
```

FWIW, I'm having trouble with the `hug.test` module in general (I get 404 responses no matter what); some clearer documentation would help.

**Comment by bachya** [comment]
I think this needs to be reopened. I've got a route that looks like this:

```Python
def get_schedule(response, calendar_url=VALID_URL):
    try:
        req = requests.get(calendar_url)
        return {'status': 'success'}
    except requests.exceptions.RequestException:
        response.status = status_codes.HTTP_504
        return {'status': 'failure'}
```

When I query this route directly, I get a 504, as expected. However, when I run a comparable test case:

```Python
def test_schedule_unreachable(self):
    result = hug.test.get(module, 'v1/schedule', params={'calendar_url': 'http://bad.url'})
    print(result.status)
```

...I get an output of `200 OK`. Am I missing something?

**Comment by timothycrosley** [comment]
Hi @bachya, I think this is simply because the params parameter is not yet distributed yet as we are waiting on on a new deploy of falcon to push a new version of hug (see: https://github.com/timothycrosley/hug/issues/403). In the mean time you could either use the development branch of hug to get support for the params option or pass in custom parameters as keyword argument:

```python
    result = hug.test.get(api_module, 'v1/schedule', calendar_url='http://bad.url')
```
or 
```python
    result = hug.test.get(api_module, 'v1/schedule', **{'calendar_url': 'http://bad.url'})
```

**Comment by bachya** [comment]
Ahh, that makes sense. Thanks for clarifying!
