### ISSUE TITLE
directives not working?

### ISSUE THREAD

**Issue by ericfrederich** [timothycrosley/hug#356]
Unless I'm doing something wrong, I copied and pasted the directive examples and got `False` for both of the `tester() == 100` statements.  It returns 10, not 100.

Am I doing something wrong?
- Hug 2.1.2
- Python 3.5.1

**Comment by spock** [comment]
@ericfrederich , you were probably testing those examples from the command line?
This is what I did, and I also got "10" instead of "100".

For me the fix (see pull request) was to add `@hug.local()` in addition to `@hug.get()` to make decorators work also from the command line.
