### ISSUE TITLE
HTTP Delete and Patch

### ISSUE THREAD

**Issue by mhavel** [timothycrosley/hug#360]
Hi Timothy,

As far as I understand, the 'delete' and 'patch' (edit: and 'put' too it seems) HTTP methods do not work properly.

```python
@hug.delete('/delete_me')
def delete_me():
    return


@hug.delete('/delete_me2')
def delete_me2():
    return {'msg': 'deleted'}
```

In both cases (and with 'patch' and 'put' methods too), I get the following error:

```log
Traceback (most recent call last):
File "hug/api.py", line 381, in hug.api.ModuleSingleton.__call__.api_auto_instantiate (hug/api.c:10677)
File "[...]/versions/3.5.2/lib/python3.5/site-packages/falcon/api.py", line 189, in __call__
responder(req, resp, **params)
File "hug/api.py", line 280, in hug.api.HTTPInterfaceAPI.version_router (hug/api.c:8023)
File "hug/interface.py", line 581, in hug.interface.HTTP.__call__ (hug/interface.c:15515)
File "hug/interface.py", line 447, in hug.interface.HTTP.gather_parameters (hug/interface.c:11449)
File "hug/format.py", line 35, in hug.format.parse_content_type (hug/format.c:915)
TypeError: argument of type 'NoneType' is not iterable
```

I ~~might~~ must be doing something wrong though: if you could point me in the right direction, that'd be awesome.
I've also read on the web that a 'delete' HTTP method could send a response body.

Best.

**Comment by timothycrosley** [comment]
HI @mhavel,

Agreed that this should work! I've tried copying and pasting exactly what's listed above and testing it with 

`curl -X DELETE http://localhost:8000/delete_me2` both on the server and client side everything worked flawlessly and I recieved the expected response `{"msg": "deleted"}`. Any more information you can provide? Any chance there is more code enough that is calling the failure?

Thank you!

~Timothy Crosley

**Comment by mhavel** [comment]
Hi @timothycrosley,

Thanks for testing on your side. Yes there is some extra code, but I don't see what could cause the issue.

Actually, a closer code snippet to what I'm actually using is:

```python
import hug
import numpy as np

auth = hug.http(requires=hug.authentication.basic(hug.authentication.verify('guest', 'letmein')))

@hug.local()
@auth.delete('/delete')
def delete(receipt:hug.types.smart_boolean=True, versions=1, examples='receipt=True'):
    """Delete method"""
    # processing stuff
    arr = np.random.sample(size=34)
    arr *= arr
    if receipt:
        return {'msg': 'deleted', 'arr_sq_mean': arr.mean()}
    else:
        return
```

When I test that locally on my computer, it works as expected indeed (both using `hug -f` and `uwsgi`). Not sure what is causing my issue in my production app, which API is not much more complex than the snippet above.
Anyway thanks for your input, if I understand the issue I'll let you know (if that's relevant to you).

Best,
Mathieu
