### ISSUE TITLE
Sending 204 With No Body

### ISSUE THREAD

**Issue by dreadwestern** [timothycrosley/hug#362]
@timothycrosley is it possible with Hug to send a 204 response with no body? Wasn't able to get it working properly over the weekend. Thx.

This seems to fail every time with a Hug exception: 
```
@delete.urls('/insurance-profiles/{insurance_profile_id}',
                 versions=1)
def delete_insurance_profile(self,
                                 request,
                                 response,
                                 insurance_profile_id: validators.uid(UIDTypes.INSURANCE_PROFILES)
                                 ):
    # resource validation and delete queries go here
    response.status = falcon.HTTP_204
    return
```

In our endpoint, to get around this, we switched back to sending a 200 status with the full representation of the resource deleted, but it would be nice in the future to allow responses with a null body.

**Comment by timothycrosley** [comment]
Hi @dreadwestern, 

hug should indeed support this! As best as I can tell, it does in the current release so it may be worth checking to see if something else is going on. In my testing for instance, chrome wouldn't respond to or show any indication that it anything happened when trying to reach a null response 204 page, even though the server correctly returned the response (so it's potentially a client issue that you are running into). I've going ahead and added this test case to the hug test suite just to be sure [1], and tried to reproduce locally. Let me know if you are able to reproduce it in the future.

Thanks!

~Timothy

[1] https://github.com/timothycrosley/hug/pull/371/files
