### ISSUE TITLE
Release 2.1.3

### ISSUE THREAD

**Issue by incognick** [timothycrosley/hug#363]
@timothycrosley  Can you push out the next release?  PyPI is pretty far behind github now.

**Comment by timothycrosley** [comment]
Hi @incognick, 

Great point! I've been away from as active as a role for a few months due to health issues, now that they are resolved I'm hoping to knock out a few of the larger issues and then knock out a release. Plan to see one by the end of next week at the latest.

Thanks!

~Timothy

**Comment by incognick** [comment]
Hi Timothy,

I'm really glad to hear you are ok! I was worried this project was
abandoned. Great to see all the activity again. Stay healthy!

-Nick
