### ISSUE TITLE
Possible to use with Django ?

### ISSUE THREAD

**Issue by stuaxo** [timothycrosley/hug#367]
Is it possible to use this with Django?

Say I have a legacy site, but I want to add an API - it would be nice to be able to use hug for this.

**Comment by timothycrosley** [comment]
Hi @stuaxo,

The answer is both yes and no :) You can definitely use hug along side a django project. You can import all the models etc and interact with the entire existing code base. The only real limitation is that you will still need a separate server running for hug itself. Let me know if you could use any more information.

Thanks!

~Timothy

**Comment by stuaxo** [comment]
Ah, I guess running without a separate server was what I was after.

**Comment by incognick** [comment]
Hi @stuaxo,

You should be able to mount hug as a wsgi app and embed inside a django app:

https://pythonhosted.org/django-wsgi/embedded-apps.html

-Nick

**Comment by timothycrosley** [comment]
@incognick, very cool! didn't know django had built in support for including other wsgi based apps.

**Comment by SafPlusPlus** [comment]
I was tinkering a bit, trying to get Hug to run with Django using @incognick 's link. I didn't have much luck. Then I thought, lets do it simpler, and just made a little application wrapper in Django's wsgi.py and manually routing a bit:

```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "censored_project_name_dev.settings")

from censored_application_name import api

django_application = get_wsgi_application()
hug_application = api.__hug_wsgi__

def application (environ, start_response):

    path = environ.get('PATH_INFO', '')

    if path.startswith('/api'):
        response = hug_application(environ, start_response)
    else:
        response = django_application(environ, start_response)

    return response
```

Seems to work, but may not be the cleanest/most integrated solution.

**Comment by kianhean** [comment]
thanks @SafPlusPlus it worked for me.
I just want to make the solution complete together with the hug code

**api.py**
```python
"""A basic (single function) API written using hug"""
import hug
import os

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "censored_project_name_dev.settings")

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()

from .models import DJANGO_MODEL

### Rest of the your code here ###
```

**wsgi.py**

```python
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "censored_project_name_dev.settings")

from censored_application_name import api

django_application = get_wsgi_application()
hug_application = api.__hug_wsgi__

def application (environ, start_response):

    path = environ.get('PATH_INFO', '')

    if path.startswith('/api'):
        response = hug_application(environ, start_response)
    else:
        response = django_application(environ, start_response)

    return response
```

**Comment by sandeep048** [comment]
How to do django user authentication?

**Comment by stuaxo** [comment]
Is Django Middleware a possible way for this to work?

**Comment by sandeep048** [comment]
Yes exactly I'm looking at middleware at the moment. Brilliant stuaxo😎. 

Guys another question how do we organize api.py file into multiple files?

**Comment by sandeep048** [comment]
Django `wsgi.py` with a toggle switch to enable or disable hug api.
`SINGLETON=True python manage.py runserver`
```
import os
from django.core.wsgi import get_wsgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
django_application = get_wsgi_application()

if os.environ.get('SINGLETON') == 'True':
    import api
    hug_application = api.__hug_wsgi__

    def application (environ, start_response):
        path = environ.get('PATH_INFO', '')
        if path.startswith('/api'):
            response = hug_application(environ, start_response)
        else:
            response = django_application(environ, start_response)
        return response
else:
    application = django_application
```
