### ISSUE TITLE
how to get the context of request

### ISSUE THREAD

**Issue by koolay** [timothycrosley/hug#372]
How to get the context of request  in all service modules? 
hug has some like `flask.g `?

user_service.py
```
import hug

##### how to get context 

```

user_controller.py
```
import hug

hug.get("/user/{id}")
def detail(request):
           
     ### write some data into the context 

```

**Comment by timothycrosley** [comment]
Hi @koolay,

Thanks for the question! The answer is that every request object has a context dictionary on it: `request.context` this is the equivelent of flasks g object - but in a cleaner less hacky way.

Thanks!

~Timothy

**Comment by koolay** [comment]
@timothycrosley 
Thanks, I got it.
