### ISSUE TITLE
POSTing JSON

### ISSUE THREAD

**Issue by baderj** [timothycrosley/hug#377]
Posting plain JSON does not work, because the variable name of the body is treated as a required parameters. For example:

```
@hug.default_input_format("application/json")
@hug.post('/test')
def test(data):    
    parsed = hug.input_format.json(data)    
    print("GOT {}: {}".format(type(parsed), repr(parsed)))
```

called with 

```
payload = {'key1': 'value1', 'key2': 'value2'}
r = requests.post("http://localhost:8000/test", json=payload) 
print(r.status_code)
print(r.text)
```

Outputs:

```
Serving on port 8000...
GOT <class 'dict'>: {'key1': 'value1', 'key2': 'value2'}
127.0.0.1 - - [16/Sep/2016 23:08:41] "POST /test HTTP/1.1" 400 62
```

and

```
400
{"errors": {"data": "Required parameter 'data' not supplied"}}
```

As expected, the `data` variable contains the json content and is correctly parsed in an object. However, the API call fails because there is no parameter named `data`.  

I also tried the to use Falcon's `request` directly, but that just hangs:

```
@hug.default_input_format("application/json")
@hug.post('/test')
def test(request):    
    raw_json = request.stream.read()
```

**Comment by incognick** [comment]
There are several _special_ directives that are injected into handlers that do not start with "hug_". These are then omitted from the argument parsing logic.  This should be documented better ( @timothycrosley I can help ) 

**Interface Directives**
- request
- response
- body
- api_version

**Try this:**
```
@hug.post('/test')
def test(body):
    print("GOT {}: {}".format(type(body), repr(body)))

api = hug.API(__name__)

response = hug.test.post(api, '/test', {"valid": "json"})
print(response.status)
```

**Output**

```
GOT <class 'dict'>: {'valid': 'json'}
200 OK
```

**Comment by timothycrosley** [comment]
Thanks @incognick for correctly answered this question! Labeling it as such so I know to come back and build of the documentation you wrote.

Thanks!

~Timothy

**Comment by jshwelz** [comment]
@incognick @timothycrosley How can I map the body json with a mashmallow schema like:
 **def post(input: userschema, response):** and use input instead of body

**Comment by XenGi** [comment]
How would I document the fields a user has to provide in the json if I don't set them as function arguments?
