### ISSUE TITLE
Offtop: Hug is running on PyPy with CPython 3.5 support:)

### ISSUE THREAD

**Issue by TiberiumPY** [timothycrosley/hug#385]
PyPy team implemented a lot of CPython 3.5 support, so it can run Falcon and Hug already

**Comment by timothycrosley** [comment]
Woah! That's great news, thanks for notifying us, I'll try to get testing and bench-marking in place soon

**Comment by TiberiumPY** [comment]
@timothycrosley but it's very unstable, be aware of it

**Comment by TiberiumPY** [comment]
@timothycrosley and the thing that it's currently not good at performance, because PyPy team firstly will implement all Python 3.5 features, and then will start work on performance

**Comment by timothycrosley** [comment]
@TiberiumPY Thanks for the info! Maybe I'll hold of on officially supported for now, and simply list is as experimentally supported - with a note that testing of it would be beneficial in preparation for official support down the line.

Thanks!

~Timothy

**Comment by TiberiumPY** [comment]
@timothycrosley I benchmarked http benchmark by myself (but changed requests number from 20000 to 100000):
https://gist.github.com/TiberiumPY/b389b0181656b98f29d53d6387663b8c

**Comment by TiberiumPY** [comment]
@timothycrosley and, btw, about tests - all pass except benchmarks/http/flask_test.py and benchmarks/http/muffin_test.py
First: because E   AttributeError: module 'sys' has no attribute 'exc_clear' (this seems to be flask issue)
Second, because: E   ImportError: No module named 'ujson'  (because PyPy3 doesn't support PyUnicode_AsUTF8AndSize atm)

So own hug tests are all passing :)
