### ISSUE TITLE
json_camelcase should support nested arrays

### ISSUE THREAD

**Issue by philipbjorge** [timothycrosley/hug#386]
```
{
  "snake_case": [
    {"nested_snake_case": 1}
  ]
}
```

Should camelcase nested_snake_case but does not

https://github.com/timothycrosley/hug/blob/7312a1e244dfd671f0e3599a60e5ec4243af4f28/hug/output_format.py#L157

**Comment by timothycrosley** [comment]
Thanks for reporting this issue! Hope to have it resolved for the next release

**Comment by philipbjorge** [comment]
@timothycrosley Thanks for accepting this issue -- I wrote it in a rush and never came back to fill it out. 
Glad there was enough info to go off of.

**Comment by timothycrosley** [comment]
Every issue, no matter how rushed helps the project improve :). This is now resolved and merged into develop ready for the next release thanks to @mikoim.

Thanks!

~Timothy
