### ISSUE TITLE
How to get filename when upload file

### ISSUE THREAD

**Issue by koolay** [timothycrosley/hug#387]
```
@api.route.post('/upload')
def upload(file, request):

    ext = mimetypes.guess_extension(request.content_type)

```

It dose not work.

**Comment by spock** [comment]
I've looked into some multipart tests, and used code similar to the below to handle uploads:
```
@hug.post('/upload')
def upload_file(body):
    """accepts file uploads"""
    # <body> is a simple dictionary of {filename: b'content'}
    print('body:')
    print(body)
    return {'filename': list(body.keys()).pop(), 'filesize': len(list(body.values()).pop())}
```

I have tested this code with a simple upload of a small text file:
```
import requests
with open('.wgetrc', 'rb') as wgetrc_handle:
    response = requests.post('http://localhost:8000/upload', files={'.wgetrc':wget_handle})
print(response.headers)
print(response.content)
```

Hope this helps.

I'll send a pull request with this example in a few  minutes.

**Comment by koolay** [comment]
@spock 
I get it, Thanks.

**Comment by timothycrosley** [comment]
Closing as the example is now in the develop branch

Thanks!

~Timothy

**Comment by 0gk** [comment]
It seems that this answer not very correct. So you get not the file name, but the name of the content section of the POST request. The file name is contained in the header of the corresponding section of the query:

`Content-Disposition: form-data; name="file"; filename="logo.gif"
`

And if the request contains any additional information, the first with the key in the key can be the name of another section, do not have any relation to the file.
