### ISSUE TITLE
type extension "multiple ints" differ for cli and http

### ISSUE THREAD

**Issue by bernhardreiter** [timothycrosley/hug#399]
The following example gives me different results on
`hug -f multiple_ints.py`
`http://localhost:8000/getInts?ints=1,2,3`
I get `"good [1, 2, 3]"`

But 

``` shell
hug -f multiple_ints.py -c getInts 12 2
bad ['12', '2']
```

``` python
"""hug example for multiple ints input."""
import hug

class ListOfInts(hug.types.Multiple):
    """Only accept a list of numbers."""

    def __call__(self, value):
        value = super().__call__(value)
        return [int(i) for i in value]

@hug.cli()
@hug.get()
def getInts(ints:ListOfInts()):
    if all(map(lambda x: isinstance(x, int), ints)):
        return "good {}".format(ints)
    else:
        return "bad {}".format(ints)

if __name__ == '__main__':
    getInts.interface.cli()
```

What am I doing wrong?
Is there a better way of doing this?

Note that the brackets in `ints:ListOfInts()` are already a bit surprising,
reading the extending example on http://www.hug.rest/website/learn/type_annotation

**Comment by sabinem** [comment]
I tried to understand this issue and I tried to try hug.types.multiple or hug.times.comma_separated_list. They both gave me an issue, that is probably responsible for the above issue as well:

Here is my code (in issue29.py:
```python
@hug.cli()
@hug.get()
def getInts1(ints:hug.types.multiple):
    return ints
```
and 
```python
@hug.cli()
@hug.get()
def getInts2(ints:hug.types.comma_separated_list):
    return ints
```
In both cases there is the same effect:
`hug -f issue29.py -c getInts1 a,b` gives me:
['1,2']
and with `http://localhost:8000/getInts1?nrlist=1,2`I get `["1", "2"]. 
I get exactly the same result for the second function `getInts2`. 
This already seems like a bug to me and I would need more documentation on how it is meant to be used: what sets multiple  and comma_separated_list apart from each other: how should they be used on the commandline or on the webinterface?

**Comment by bernhardreiter** [comment]
@sabinem from reading the code (current master) I can see that comma_separated_list is a subclass of Multiple(), thus it will share the same problem. comma_separated list "splits up the passed in value based on the provided delimeter" so the difference probably is that you could do something like
`hug -f issue29.py -c getInts1 1°2°3` with a delimiter of `°`, whereas Multiple will only accept the build in separators for lists.

class Multiple is a subclass of Type and does not do much, so the problem most likely will be within the handling for the different outputs/apis http and cli.

**Comment by sabinem** [comment]
@bernhardreiter: I think I will quit for now, but understanding how this is constructed still interests me. What I have found out so far is that in your case above, `parser.add_argument(*args, **kwargs)` is called with: `args: ('ints',)  and kwargs: {'type': <hug.types.Text object at 0x10072e260>, 'nargs': '*', 'help': 'Only accept a list of numbers.'}` and  your class `ListOfInts`is never even called. 

In the case of the Interface being HTTP, your class is called and as you noticed things work out well. 

In case of the CLI interface the arguments are somehow calculated outside actually calling the types so your overwritten type is just not called and can't change anything. 

That to me seems to be the error: the overwrite should be called with either interface. But it takes a while to understand code that you have not written yourself, at least for me, so I am not yet sure how to fix this problem, even though I would love to work on it further, but I would probably need some guidance. 

Hope this helps a least a little. I would like to contribute, but I feel like a bloody beginner regarding  contributing to Open Source Projects.

**Comment by bernhardreiter** [comment]
@sabinem :)
With hug I'm not familiar myself. With Free Software development I am.
If you want to contribute, just go ahead and try.

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make its way into the next release.

Thanks!

~Timothy
