### ISSUE TITLE
upgrade falcon dep to 1.1.0

### ISSUE THREAD

**Issue by shomodj** [timothycrosley/hug#403]
there is a official release of falcon 1.1.0

**Comment by butla** [comment]
It's also worth mentioning that Falcon 1.1.0 has a nice TestClient that can be composed into hug.test, replacing most of the logic.

**Comment by timothycrosley** [comment]
The big problem is that Falcon 1.1.0 has a major blocking production issue that has not been resolved: https://github.com/timothycrosley/hug/issues/406. We have been building development against 1.1.0 since introduction but need to wait for a new Falcon build to feel safe updating the hug requirement. @kgriffs, what's the timeline for a new Falcon release?

**Comment by kgriffs** [comment]
Hi @timothycrosley, 1.2 is waiting on a final bug fix dealing with URI templates that should land over the next few days and then we can cut a release candidate for testing. I want to make sure it works for you before we do the final release.

**Comment by timothycrosley** [comment]
Thanks @kgriffs!

I'll start building against falcon development branch in preparation

~Timothy

**Comment by kgriffs** [comment]
Falcon 1.2.0rc1 is now up on PyPI. Please let me know if you run into any blocking issues and we'll get them fixed. Thanks!

**Comment by timothycrosley** [comment]
So far everything is looking great on the release candidate, I'll let you know if anything changes, thanks!

**Comment by kgriffs** [comment]
OK, sounds good. I'm going to go ahead and release 1.2.0. If anything comes up, we can do a quick bug-fix release to take care of it.

**Comment by timothycrosley** [comment]
Thanks @kgriffs! Everything still looks good. Went ahead and deployed a new release of hug that depends on 1.2.0, can now close this issue

**Comment by carlwgeorge** [comment]
[Falcon 1.3](https://github.com/falconry/falcon/releases/tag/1.3.0) is out.  Should new issues be filed here every time falcon is updated?  Or would it be more prudent to just change [the dependency to `falcon>=1.2.0`](https://github.com/timothycrosley/hug/blob/2.3.0/setup.py#L105)?
