### ISSUE TITLE
Returning None for File output type throws TypeError: stat: can't specify None for path argument

### ISSUE THREAD

**Issue by philipbjorge** [timothycrosley/hug#412]
https://github.com/timothycrosley/hug/blob/develop/hug/output_format.py#L229

This branch needs to handle None properly.

**Comment by cag** [comment]
What is a proper response for a web server returning no file, where the MIME could be anything? Is it no content, not found, or a 0 length plain/text or application/octet-stream?

**Comment by timothycrosley** [comment]
This is now fixed in develop and will make it's way into the next release; I will therefore close this issue, thanks for reporting! 

The approach taking is to return a blank text/plain file when None is returned

Thanks!

~Timothy
