### ISSUE TITLE
Add a CORS middleware

### ISSUE THREAD

**Issue by sseemayer** [timothycrosley/hug#421]
Hello and thanks for this beautiful library!

While working on some microservices based on hug, I ran into the situation where I would like to enable CORS by providing the appropriate `Access-Control-Allow-*` headers both in the regular replies and also enable CORS preflight requests using `HTTP OPTIONS`. I thought that the best way of doing this would be to provide a response middleware that might also be of use for others.

Would you be generally willing to accept a PR for such a middleware to the main hug repository, or would you prefer this to be implemented in a hug extension `hug_middleware_cors` in a separate repository?

**Comment by sseemayer** [comment]
Here's what I have so far:

https://github.com/sseemayer/hug_middleware_cors

Is there a better way of retrieving the current API from a middleware so that it can retrieve the registered routes?

**Comment by spock** [comment]
Just my 2¢: as [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) is directly related to consuming web-APIs, and Hug is great for developing web-APIs, it would make sense to have this middleware included in Hug.

**Comment by timothycrosley** [comment]
Thank you! I agree with spock about including this middleware, as a built in if that is okay with you. There is an additional way to use cors, currently but it requires keeping around a custom router, which may not be as useful for some peoples application architectures:
```
my_router = hug.http().allow_origins('google.com')

```

**Comment by timothycrosley** [comment]
This is now included as of the lastest version of hug.

Thanks @sseemayer for the great work!

~Timothy
