### ISSUE TITLE
[question] how to render template

### ISSUE THREAD

**Issue by robsonpeixoto** [timothycrosley/hug#422]
I'd like to use it to build a REST api and a webapp on the same application.
Is it possible? how?

**Comment by philipbjorge** [comment]
@robsonpeixoto We're doing this right now...
We have...

`support/templates.py`
```
from jinja2 import FileSystemLoader, Environment

template_engine = Environment(loader=FileSystemLoader("templates"))

def get_template(name):
    return template_engine.get_template(name)
```

`controllers/deals.py`
```
from support.templates import get_template

@hug.get(versions=1, output=hug.output_format.html)
def details(id : hug.types.text):
    template = get_template("deals.html")
    return template.render({})
```

This is using the jinja template engine.

It's also possible to pass in jinja as a hug directive, but then we lose pycharm intellisense support.

Enjoy!

@timothycrosley -- Is there a good place to put an example like this?

**Comment by spock** [comment]
@philipbjorge , there is the [examples folder](https://github.com/timothycrosley/hug/tree/develop/examples) with small and easy to run hug examples. I guess jinja template rendering could be added there.

**Comment by jkornblum** [comment]
@philipbjorge How do you render static files like js or img like this without specify a route for each one?

E.g. my html has
` <script type="text/javascript" src="/static/js/main.83546794.js"></script>`
but although the file is there I get a 404. I'm assuming this is a hug issue where there isn't a route defined.

**Comment by philipbjorge** [comment]
@jkornblum -- You'll want to front your hug server with nginx or apache.

**Comment by spock** [comment]
@robsonpeixoto , it's also possible to [serve an entire directory of static files](https://github.com/timothycrosley/hug/pull/429), using hug.

**Comment by timothycrosley** [comment]
Marking this as a question so it can be added to documentation, and losing as I think it was correctly answered.

Thanks!

~Timothy
