### ISSUE TITLE
How to serve static files in a directory

### ISSUE THREAD

**Issue by bernhardreiter** [timothycrosley/hug#425]
It would be nice if there was an example how to serve static files from a directory from within hug, so that other hug mechanisms, like authentication work. This can be needed to load a single page web application. (For example I am using hug as a prototyp serving backend in https://github.com/Intevation/intelmq-fody  where it would be useful to serve the static files.)
 
In  https://github.com/timothycrosley/hug/issues/43#issuecomment-197343923 the need for this can be seen. (There not solved by hug, but by pecan using `static`..)

**Comment by spock** [comment]
There is an [example of serving an image file](https://github.com/timothycrosley/hug/blob/develop/examples/image_serve.py) using hug (path to served image is wrong and fixed in https://github.com/timothycrosley/hug/pull/426). For a static HTML page one would only need to set proper output format: `output=hug.output_format.html`.

Does this solve the issue? If not, then what would you change/improve?

**Comment by bernhardreiter** [comment]
@spock thanks for your consideration!

The example is about one single file, I would like to serve all files from a directory without
the need of specifying each file separately.

**Comment by bernhardreiter** [comment]
It already works as the example in my pull-request #429 show. 
I'd say it misses a bit of documentation.

a) the function decorated with hug.static() seems to be called before hug.startup() functions.
Is it only called once?

b) how are the filetypes determined?

**Comment by spock** [comment]
regarding b), I'd guess its [output_format.file](https://github.com/timothycrosley/hug/blob/develop/documentation/OUTPUT_FORMATS.md#built-in-hug-output-formats)

**Comment by teran-mckinney** [comment]
Not having any luck with this using a PNG file. Is there another recommended way to do this?

```
@hug.get('/static/{static_file}', output=hug.output_format.file)
def static(static_file):
    if '..' in static_file:
        raise
    return open('static/{}'.format(static_file))
```

Thank you!

**Comment by bernhardreiter** [comment]
@teran-mckinney if you are trying **to serve all files** from a directory, then consider trying my example code at https://github.com/timothycrosley/hug/pull/429 . Should be something like (untested):

```python
@hug.static('/static')
￼def my_static_dirs():
￼    return('/home/www/path-to-static-dir',)
```

**Comment by teran-mckinney** [comment]
@bernhardreiter thank you, that worked!

https://github.com/sporestack/launch.sporestack.com/commit/1f81cf12dbf3e369b3fd6fd84c950cac33ee580d

**Comment by m-ueno** [comment]
Another solution here.
How about using `werkzeug.wsgi.DispatcherMiddleware` ?

https://gist.github.com/m-ueno/0ec3922c30c37424f13bcaecc98ab4db

**Comment by timothycrosley** [comment]
Looks like this question has been answered well, closing and will remember to expand the documentation, thanks everyone!
