### ISSUE TITLE
Support automatic reload on file change

### ISSUE THREAD

**Issue by timothycrosley** [timothycrosley/hug#43]
Split off from here: https://github.com/timothycrosley/hug/issues/31. Ideally, hug would automatically restart a dev API when the files used to create it changed. This would streamline the user workflow when using hug.

**Comment by arthurk** [comment]
Here's a recent discussion about auto-reloading on the django-developers mailing list: https://groups.google.com/forum/#!topic/django-developers/voXNIDdDcpU. It has a few good ideas on how to improve Django's auto-reloading, but it might be useful for Hug too

**Comment by timothycrosley** [comment]
@arthurk, I think that's super helpful as we think about how to implement hug's solution. Thanks for finding and sharing!

~Timothy

**Comment by sloria** [comment]
There is a WIP PR for a debug server in falcon: https://github.com/falconry/falcon/pull/517

**Comment by timothycrosley** [comment]
@sloria thanks for linking! Hopefully will be able to get this in for the 2.0.0 release :)

**Comment by PrashntS** [comment]
In a recent project, I'd needed needed both Auto Reload and Static file serving capabilities.
Using hug, this is the solution I came up with.

- Use `static` for a WSGI compatible static file handling.
- Write the API as usual using `hug`.
- Use `pecan_mount` to mount `__hug__` and `static` to a single WSGI point.
- Run this with `gunicorn`'s Auto Reload turned on.

And there, a quick and easy solution. :laughing: 

Here's a snippet in case anybody's interested.

```python
import hug
import pecan_mount
import static

@hug.get('/', versions=1)
def get_root():
  return True

# Mount Hug at `/api` and static files at '/'
pecan_mount.tree.graft(__hug_wsgi__, '/api')
pecan_mount.tree.graft(static.Cling("/path/to/static/root"), '/')

app = pecan_mount.tree
```

Running with `gunicorn`: `$ gunicorn module:app --reload`

I'm looking forward to version 3, though!

**Comment by samstav** [comment]
FWIW, here's a link to the relevant code in the latest release of bottle:

https://github.com/bottlepy/bottle/blob/0.12.9/bottle.py#L3131-L3161

**Comment by timothycrosley** [comment]
Closing this as this feature is now completed in development and ready for the next release.

Thanks!

~Timothy
