### ISSUE TITLE
When using Marshmallow schemas with POSTed JSON, no input docs are generated

### ISSUE THREAD

**Issue by philipbjorge** [timothycrosley/hug#433]
```
    @hug.post('/{}'.format(url_name), versions=1)
    def create_or_update(body: SomeSchema()):
        pass
```

No docs are generated for the input

**Comment by cag** [comment]
Does `SomeSchema` have a docstring?

**Comment by timothycrosley** [comment]
@cag is pointing to the correct answer, hug will show documentation assuming documentation (a doc string) is present. Otherwise it is hard to do so in an officiant manor.

**Comment by dangitall** [comment]
I see this issue too whether there is a docstring in the schema or not. It looks like it is being explicitly excluded here: https://github.com/timothycrosley/hug/blob/e7eccc252b89b66107772021b610da07e556e4fb/hug/interface.py#L256

Can someone explain why body would be excluded?
