### ISSUE TITLE
Adapt output serialisation based on return type

### ISSUE THREAD

**Issue by sdementen** [timothycrosley/hug#434]
Is it possible to specify the serialization of a given type for a given output format ?
I have functions returning pandas DataFrames and I would line to specify how to serialize them in json, html, csv, etc.
I found no obvious way to do it in the doc or the examples

**Comment by cag** [comment]
Here is one way you can do this, assuming you are creating a web API: create a custom output formatter which accepts a tuple containing the following values: the format type and the `DataFrames` object. Set the mime-type and call a formatting method on the object accordingly. Which format you serialize in is up to you, though I have seen APIs which accept a `format` url parameter, and I have heard of APIs which look at the `ACCEPTS` HTTP request header.

Alternatively, you could have multiple functions with different routes for the different formats. You may still want to create an output formatter though (to set the mime-type).

**Comment by timothycrosley** [comment]
@cag is correct, and in fact hug includes a helper function to enable this easily, 
You can see an example of this approach here:

https://github.com/timothycrosley/hug/blob/develop/tests/test_output_format.py#L217

Thanks!

~Timothy
