### ISSUE TITLE
Pattern for complex routes (hierarchical sub-routes, resources...)

### ISSUE THREAD

**Issue by stefanocrosta** [timothycrosley/hug#436]
Hello!

I understand the documentation is still in its infantry, so this might end up being in v3, but do you have best practices for more complex routing patterns?

EG.

```
/api/vision/classify
/api/vision/train
/api/admin/
/api/sound/classify
/api/sound/train
```

(maybe one of the answers is the /api/ at the beginning should be in a reverse proxy frontend such as nginx, but a hierarchical pattern is still useful)

Also there is little suggestions on best way to deal with resource patterns such as 

`/api/resources/{resourceId}`

but also

`/api/resources/{resourceId}/somethingelse/{}`

My files are growing a bit wild trying to put something together...!

I'm used to django way of dealing with routes and resources, which I find clean and flexible, but I find overkill bringing in the full framework for many modern projects with a leaner api and no need for complex database layer and templating system; and was seduced by the different approach Hug is taking; but without more documentation (or a larger sample project maybe?) I am really struggling with more complex scenarios...

thx!

**Comment by cag** [comment]
I agree that the documentation for this sort of thing is a bit sparse right now. There is a thing called `extend_api` which might help. See the following snippets from the test cases:

```python
def test_extending_api():
    """Test to ensure it's possible to extend the current API from an external file"""
    @hug.extend_api('/fake')
    def extend_with():
        import tests.module_fake
        return (tests.module_fake, )

    assert hug.test.get(api, 'fake/made_up_api').data


def test_extending_api_simple():
    """Test to ensure it's possible to extend the current API from an external file with just one API endpoint"""
    @hug.extend_api('/fake_simple')
    def extend_with():
        import tests.module_fake_simple
        return (tests.module_fake_simple, )

    assert hug.test.get(api, 'fake_simple/made_up_hello').data == 'hello'
```

(Also see `module_fake.py` and `module_fake_simple.py` in the test cases.)

**Comment by bernhardreiter** [comment]
There is an example at https://github.com/timothycrosley/hug/blob/develop/examples/secure_auth_with_db_example.py using
```python
@hug.get(('/api/job', '/api/job/{job_id}/'), requires=api_key_authentication)
```
showing that ```/api/resources/{resourceId}``` works. (Note that https://github.com/timothycrosley/hug/pull/449 must be merged for the full example to work.)

**Comment by stefanocrosta** [comment]
@bernhardreiter thanks, that's not what I'm after - I understand how a to use a variable from the REST url but I was after ways to extend a the paths, basically what Django calls "including" other URL confs (https://docs.djangoproject.com/en/1.10/topics/http/urls/#including-other-urlconfs).

@cag answer is on topic, and I still think it deserves full space in the documentation! (and it's a bit unusual :-) )

**Comment by timothycrosley** [comment]
Support for this is now in develop and will make it's way into the next release:

see: https://github.com/timothycrosley/hug/issues/464 for more details.

Essentially you can now include parent URLs simply by using relative paths:

```python
    my_router = hug.urls('/base_route')

    @my_router.get('sub_route')
    def my_method(*args, **kwargs):
        pass
```
would result in my_method being accessible via the url `/base_route/sub_route`.
Let me know if this doesn't fully address your issue.

Thanks!

~Timothy
