### ISSUE TITLE
Global HTTP router state breaks unit tests' isolation

### ISSUE THREAD

**Issue by butla** [timothycrosley/hug#437]
I've created a sample app specifically to check out how to do REST resource testing in Hug.
I know that it's possible to validate the pure Python functions that handle the requests,
but it's just not sufficient in all cases.
Also, I've noticed that there is a test client in hug.test just now as I'm writing this issue. I started off with the one from Falcon 1.1.0. Changing it to the "original" Hug one isn't helping.

On to the issue: I'm recreating the API object for each subsequent test with the [code here](https://github.com/butla/experiments/blob/master/hug/app/tests/test_unit.py#L17), which actually calls [this](https://github.com/butla/experiments/blob/master/hug/app/contact_list/app.py#L43). As you can see, I'm using pytest fixtures that create a new mock instance for each new resource object ([ContactList](https://github.com/butla/experiments/blob/master/hug/app/contact_list/app.py#L16)), for every test.

From what I've seen, on later tests, requests will be routed to an older
(not the one created for the current test) `ContactList` object.
This makes [test_get_missing_contact](https://github.com/butla/experiments/blob/master/hug/app/tests/test_unit.py#L34) and
[test_post_contact](https://github.com/butla/experiments/blob/master/hug/app/tests/test_unit.py#L48) fail, because the older `ContactList` created for a different test interacts with a different mock object.

I've tried to find the offending Hug lines precisely, but the code that sets up routing
is so complicated, that I wasn't able to do it in a few hours.

Reproduction:
```bash
git clone https://github.com/butla/experiments
cd experiments/hug/app/
virtualenv -p python3 hug_sample
. hug_sample/bin/activate
pip install -r requirements.txt -r tests/requirements.txt

# see success when running a single test:
py.test tests/test_unit.py -k test_post_contact -v
# see failure when running multiple ones:
py.test test/test_unit.py -v
```

Hope I'm not missing something obvious...

**Comment by timothycrosley** [comment]
Hug APIs are singletons per a module, this is made explicit by the usage of `__name__` when retrieving the API. You can assign custom names to guarantee global uniqueness, and in the next version you will be able to do hug.API() to create a truly anonymous API.

**Comment by timothycrosley** [comment]
For reference: this is now support here and will be ready https://github.com/timothycrosley/hug/pull/481 for the next release.

Thanks!

~Timothy

**Comment by butla** [comment]
@timothycrosley That's good news, thanks!
