### ISSUE TITLE
Errors in /website/learn/routing: s/external/internal/.

### ISSUE THREAD

**Issue by ctwardy** [timothycrosley/hug#439]
The [/learn/routing](http://www.hug.rest/website/learn/routing) documentation page has two examples beginning:
```
# external.py
import hug

import external
```
I believe `import external` should be `import internal` to invoke the "Internal API" defined previously.  Likewise, the calls to `external.root` should be `internal.root`, because that is where `root` is defined.

I also noticed two simple typos in the main text:
* extreamly -> extremely
* convience -> convenience

I tried a quick `git clone` but I don't think these docs are in git, and something wasn't right with my environment, so I'm just filing this ticket.

**Comment by timothycrosley** [comment]
Thanks for reporting these issues! They are now all resolved on the live website.

Thanks!

~Timothy
