### ISSUE TITLE
Hug initialization

### ISSUE THREAD

**Issue by birnbaum** [timothycrosley/hug#446]
I'm struggling to understand how to initialize stuff after starting hug with gunicorn:
`gunicorn -b :8000 server.xyz:__hug_wsgi__`

It seems that no code in my hug python file is executed at all until the first request comes in. Even code that I put under `@hug.startup()` is only executed right before the request itself is processed but not on server startup.
This causes the first request after a server restart to be delayed by ~15s (thats how long the init takes) to respond. Every following request works just fine.

Am I doing anything wrong or is this a bug? I'm not sure if this behaviour is related to hug or gunicorn.
Thanks a lot!

**Comment by timothycrosley** [comment]
I don't believe that there is anything within the WSGI spec that allows us to distinguish a server is being started (as a separate thing from the first request), and know for sure the intent is for the module to be served (what startup is for) and not simply imported. Really, ideally, startup items shouldn't take 15 seconds, but in the real word they definitely can, in this case no matter what your approach is your increasing recovery time of a service by that amount. There's 2 ways to try to mitigate this: you could achieve pre-request instantiation simply by doing it at import time by moving the startup steps outside of the function, or you could automate a throwaway call to each service process immediately after a (re)start.

Thanks!

~Timothy

**Comment by gushecht** [comment]
> I don't believe that there is anything within the WSGI spec that allows us to distinguish a server is being started (as a separate thing from the first request), and know for sure the intent is for the module to be served (what startup is for) and not simply imported. Really, ideally, startup items shouldn't take 15 seconds, but in the real word they definitely can, in this case no matter what your approach is your increasing recovery time of a service by that amount. There's 2 ways to try to mitigate this: you could achieve pre-request instantiation simply by doing it at import time by moving the startup steps outside of the function, or you could automate a throwaway call to each service process immediately after a (re)start.
> 
> Thanks!
> 
> ~Timothy

@timothycrosley – could you explain how to do this pre-request instantiation?

**Comment by gushecht** [comment]
This seems to work, as a gunicorn server hook, but I'm not sure if it's the recommended approach :)

```py
from gunicorn.http.wsgi import Response, default_environ
from unittest import mock


def on_starting(arbiter):
    mocked_request = mock.MagicMock()
    mocked_request.path = '/'

    mocked_socket = mock.MagicMock()
    mocked_socket.sendall = mock.MagicMock()

    mocked_cfg = mock.MagicMock()
    mocked_cfg.workers = 2  # so that gunicorn sets wsgi.multiprocess to True

    env = default_environ(mocked_request, mocked_socket, mocked_cfg)

    env.update({
        ... various vars ...
    })

    response = Response(mocked_request, mocked_socket, mocked_cfg)
    arbiter.app.wsgi()(env, response.start_response)
```

Apologies in advance if you feel that this question contains too much in the way of gunicorn particulars.

**Comment by gushecht** [comment]
I think I figured out how to do pre-request instantiation.

We're doing the work of `api_auto_instantiate` by putting this at the bottom of the module that defines the WSGI callable that gunicorn runs:
```py
# app.py
if '__hug__' in globals():
    globals()['__hug_wsgi__'] = globals()['__hug__'].http.server()
```

(Assuming I'm starting gunicorn with`gunicorn app:__hug_wsgi__`)

**Comment by gushecht** [comment]
In case anyone finds this helpful, we've been live with this change above to do pre-request instantiation for over a week with no issues.

We are using gunicorn's `--preload` option, as well.
