### ISSUE TITLE
How to auto reload

### ISSUE THREAD

**Issue by sloweclair** [timothycrosley/hug#450]
I noticed that the code supports auto reloading when file changes, but I couldn't figure it out. The cli help doesn't state how to do it either.

**Comment by banteg** [comment]
You can any wsgi server that supports auto-reload, for example:
```
gunicorn --reload app:__hug_wsgi__
uwsgi --py-autoreload 1 --http :8000 -w app:__hug_wsgi__
```

**Comment by davidhyman** [comment]
You can also bootstrap it off other libraries inline like so (e.g. with https://bottlepy.org):
```
import hug
from bottle import run
# (define or import some endpoints)
callable_app = __hug__.http.server()
run(app=callable_app, reloader=True, port=8765)
````
Wouldn't recommend this for production but it'll do for development (don't know if / when Hug will get its own reloader).

**Comment by timothycrosley** [comment]
This feature has been completed, but is awaiting the next release to become available. Until then, and really even after that point, @banteg's recommended approach is solid.

Thanks!

~Timothy
