### ISSUE TITLE
Grabbing the request referer?

### ISSUE THREAD

**Issue by teran-mckinney** [timothycrosley/hug#453]
Hi,

Is there a way to retrieve the HTTP referer header with Hug? Seemed like that didn't exist even in Falcon, so I imagine not.

Thank you,
Teran

**Comment by banteg** [comment]
Hi, referrer is in request headers, so you can access it with `request.headers.get('REFERER')`

**Comment by teran-mckinney** [comment]
Thank you, that worked!
