### ISSUE TITLE
how to configure hug application in PyCharm

### ISSUE THREAD

**Issue by chopanpma** [timothycrosley/hug#460]
Hi, I am new to python and I have tried to configure my hug application to use PyCharm for debugging, however I have not been able to determine the startup script that work with PyCharm .
![2017-02-21 10_57_33-run_debug configurations](https://cloud.githubusercontent.com/assets/11821909/23172710/a8d71ca4-f824-11e6-921a-981af4d79be1.png)

**Comment by Evolution0** [comment]
Unfortunately with the way hug code is run (`hug -f FILE`) you have to attach the debugger to the process, first step would be making the run process more convenient, I suggest creating a new External Tool preset like this: 
![hug](https://cloud.githubusercontent.com/assets/1984403/23215308/e29d8a66-f8df-11e6-9a9b-0bbeb33970f7.PNG)

Makes it a bit simpler to get running, once its running you would then use the Run > Attach to local process feature. Keep in mind it apparently only works for Python 3.4.4 and older.

**Comment by chopanpma** [comment]
Thanks,

**Comment by davidhyman** [comment]
If it helps, this alternative approach also seems to behave like any other wsgi server for PyCharm, and happily handles debugging, code coverage etc. Setup is as simple as pointing PyCharm at this server. Can vouch for it on Python 3.5, 3.6:
https://github.com/timothycrosley/hug/issues/450#issuecomment-279685321

**Comment by timothycrosley** [comment]
Closing this as it seems to have been satisfactorily answered. Thanks!
~Timothy

**Comment by joshnoe** [comment]
@davidhyman "Setup is as simple as pointing PyCharm at this server."

How do you do this? If the comment you've linked to is related, I'm not following it.

**Comment by timwah** [comment]
FWIW here's what I ended up doing to run/debug from PyCharm:
```
from werkzeug.serving import run_simple

import api


def create_app():
    return api.__hug_wsgi__


app = create_app()

if __name__ == '__main__':
    run_simple('0.0.0.0', 5000, app, use_reloader=True, use_debugger=True, threaded=True)
```
