### ISSUE TITLE
@hug.startup() has no effect in some cases

### ISSUE THREAD

**Issue by Evolution0** [timothycrosley/hug#461]
Based on the example this should work:

```python
session = None
headers = None

@hug.startup()
async def init(api):
    session = aiohttp.ClientSession()
    headers = {'user_agent': 'foo/bar (https://github.com/Evolution0)'}

@hug.cli()
@hug.get()
async def test():
    return session, headers
```
Using: `hug -f filename.py`
Output: `(None, None)`

Adding an `if __name__ == '__main__':` `calling init(hug.API('cli))` then running test does not work either.

Declaring `session` and `headers` as **global** in `init` and doing the same *does* work-- however this does not help when using `hug -f`.

It seems `@hug.startup()` simply doesn't do anything in some cases, I say "some" because other user have gotten it working for the API but conversely not for the CLI without a workaround: #405

Temporarily I've fallen back to simply making my init function local and awaiting it before every api call.

**Comment by timothycrosley** [comment]
Support this is now in the develop branch and ready for the next release,
Thanks!

~Timothy
