### ISSUE TITLE
List Routes

### ISSUE THREAD

**Issue by shakna-israel** [timothycrosley/hug#462]
Is there a way to get a list of routes from either ```__hug_wsgi__``` or ```hug.API```?

**Comment by timothycrosley** [comment]
Hi @shakna-israel,

you can get a list of routes by looking at the routes object on the http api:

`__hug_wsgi__.http.routes`

It returns a structure of base_url -> url -> HTTP method -> Version -> Python Handler

so if, for instance, you had no base_url set and you wanted to see all URLs, you could do:

`__hug_wsgi__.http.routes[''].keys()`

Hope this is helpful!

Thanks!

~Timothy
