### ISSUE TITLE
A fallback default route if no other matches?

### ISSUE THREAD

**Issue by bernhardreiter** [timothycrosley/hug#466]
Right now there is
```python
documentation_404()
```
to be called if not other http route is found.

For single page applications it makes sense to be able to configure a different default to be served
and to call documentation_404() only for certain parts of the routes. Examples

 * Route `/api/contactdb/{id}' to a regular function
 * Route `/static` to a directory.
 * Route `/api/` default to documentation_404()
 * Route everything else to the file `index.html` to let the SPA handle it

**Comment by banteg** [comment]
You can use `@hug.sink('/')` decorator to create a catch-all route.

**Comment by bernhardreiter** [comment]
@banteg Thanks for the hint, once I get back to this point I'll try if sink() can help me with the use case.
In any case `sink()´ should be mentioned in the documentation, I believe.

**Comment by timothycrosley** [comment]
Hi @bernhardreiter, @banteg is correct to recommend sink usage and you are correct that it should be in the documentation. I'll be adding documentation based on every issue marked with `question` over the coming weeks.

Thanks!
