### ISSUE TITLE
localhost serve doesn't work (on Windows?)

### ISSUE THREAD

**Issue by simplynail** [timothycrosley/hug#470]
Hi there,
first of all - great work! I'm new to web programming and Hug eases stuff a lot!

I am having a problem running simple dev server on Windows.
I am simply running unmodified the code from:
https://github.com/timothycrosley/hug/blob/develop/examples/quick_server.py
and I get following error:

> ...
>   File "C:\Python34\WinPython-64bit-3.4.4.2Qt5\python-3.4.4.amd64\lib\socketserver.py", line 444, in server_bind
>     self.socket.bind(self.server_address)
> OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

Any thoughts on what may cause it?

**Comment by cag** [comment]
I think you'll have to open that port in your firewall for python.

**Comment by simplynail** [comment]
Fair enough, I didn't get any prompt from firewall that Python requests access to new port so didn't catch that. It works now, thanks!

BTW 
is there some simple way to bind dev server to some other port than default 8000?
