### ISSUE TITLE
For some reason `json` is not a member on `hug.types` in hug 2.2.0

### ISSUE THREAD

**Issue by kootenpv** [timothycrosley/hug#475]
The editor complains.

**Comment by timothycrosley** [comment]
Hi @kootenpv!

Which editor are you using that complains about this?

Just verified, that it should indeed be present: 
```python
In [1]: import hug

In [2]: hug.types.json
Out[2]: <hug.types.JSON at 0x7fc0e49f69c0>

In [3]: hug.__version__
Out[3]: '2.2.0'

```

**Comment by kootenpv** [comment]
My apologies for confusing. It's pylint who is confused about it. Just have
a file with your code example and it'll complain.

**Comment by timothycrosley** [comment]
Pylint is indeed very picky. If you can give me the exact code snippet that is failing I can provide more directions, forward the issue to the pylint team if necessary or fix it if it is indeed a problem with hug.

For now:
```
printf '"""testing pylint"""\nimport hug\n\nprint(hug.types.json)\n' > test.py
pylint test.py

Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |0      |1        |-1.00      |
+-----------+-------+---------+-----------+
|refactor   |0      |0        |=          |
+-----------+-------+---------+-----------+
|warning    |0      |0        |=          |
+-----------+-------+---------+-----------+
|error      |0      |0        |=          |
+-----------+-------+---------+-----------+



Global evaluation
-----------------
Your code has been rated at 10.00/10
```

Without more information I'm afraid I'll have to close the issue for now.

Thanks!

~Timothy

**Comment by kootenpv** [comment]
No problem, I understand and checking for so far. Indeed, the simple example is apparently not the issue.

This particular combination (I think because of cors) *does* give a problem!

```
import hug


def cors_support(response, *args, **kwargs):
    response.set_header('Access-Control-Allow-Origin', '*')


@hug.local()
@hug.post('/give_answers', requires=cors_support)
def give_answers(question: "a question", context: hug.types.json):
    return 1
```
