### ISSUE TITLE
Test module doesn't handle API versioning

### ISSUE THREAD

**Issue by bachya** [timothycrosley/hug#477]
In file `api_module1.py`, I have this route defined:

```Python
@hug.get('/test', versions=1)
def test():
    return 'test'
```

When I run a `hug.test`-based test, it doesn't work:

```Python
t = hug.test.get(api_module, '/test')
# t.status == 404 Not Found
```

If I remove the `versions` parameter:

```Python
@hug.get('/test')
def test():
    return 'test'
```

...things work as expected:

```Python
t = hug.test.get(api_module, '/test')
# t.status == 200 OK
```

I dug through `hug/test.py` and couldn't find anything relating to versions in the route.

**Comment by bachya** [comment]
Ended up finding an answer to my own question by hunting through `test_directives.py`. For anyone else stumbling across this, this change gave me what I wanted:

```Python
t = hug.test.get(api_module, 'v1/test')
# t.status == 200 OK
```

**Comment by timothycrosley** [comment]
@bachya Thanks for this! Adding the question label so I, and others searching, can know that it contains useful documentation

**Comment by wordtracker** [comment]
I got caught out by this just now as well. Wouldn't it be more intuitive to allow 'test/v1' instead of 'v1/test' so it matches the 404 docs page? 
(btw, am loving Hug, so so good, thanks for making it)

**Comment by kwilcox** [comment]
Just a side note for others finding this, you can specify `None` as a version to get it to revert to the unversioned URL. In this case `@hug.get('/test', versions=(None, 1))` would allow both `hug.test.get(api_module, '/test')` and `hug.test.get(api_module, 'v1/test')` to work.
