### ISSUE TITLE
doco says port 8080 but default is 8000

### ISSUE THREAD

**Issue by tcab** [timothycrosley/hug#48]
The initial example in the doco says
localhost:8080/happy_birthday?name=Hug&age=1
but the default is 8000 causing initial confusion.
Not a biggie but might confuse newcomers.

**Comment by timothycrosley** [comment]
Thanks for reporting this! Will fix ASAP

**Comment by timothycrosley** [comment]
Fixed :) thanks for catching and reporting this!

~Timothy
