### ISSUE TITLE
Request headers and content negotiation

### ISSUE THREAD

**Issue by jonathanunderwood** [timothycrosley/hug#482]
Is it possible with hug to retrieve request headers? I see it's possible to retrieve the request body, but nothing about the headers. I ask in the context of wanting to set up endpoints which perform content negotiation based upon the ACCEPT header. Is this a pattern you've considered as a use case for hug at all?

**Comment by timothycrosley** [comment]
Hi @jonathanunderwood,

You can indeed get the accept headers on a request and within output for matters off of the request object, and there is a pre-built {accept: output_format} enabling output format defined here: https://github.com/timothycrosley/hug/blob/develop/hug/output_format.py#L274, you can see example usage defined in its test case here: https://github.com/timothycrosley/hug/blob/develop/tests/test_output_format.py#L217, note that every hug request object, is using a Falcon request object to power it, so you can get a pretty good definition of what to expect here: http://falcon.readthedocs.io/en/stable/api/request_and_response.html#falcon.Request.

Hopefully this is helpful,

Thanks!

~Timothy
