### ISSUE TITLE
hug client

### ISSUE THREAD

**Issue by kootenpv** [timothycrosley/hug#486]
I'm wondering if it would make sense if hug could accommodate a client library?

Since you are able to produce an index which is aware of a lot of information, would it not be somehow possible for something like:

```python
# /some_route exists in the server
from hug.client import RequestsClient
client = RequestsClient("/path/to/hug/definition.yaml") # yaml generated based on a "hug -f"
client.some_route(arg1, arg2, arg3)
```
`requests` is here used as a backend for example, but perhaps hug would be able to make a choice for that, similarly to how the `falcon` choice was made as a server.

Curious to other people's thought.

Perhaps it wouldn't choose for requests, but would only be able to generate some client definition.

Note that I had a particular case where I was not able to use `@local`, but I had to instead use HTTP calls.

**Comment by timothycrosley** [comment]
This is indeed a goal of hug! But certainly requires more, and better documentation, you can see the introduction of this feature on hug.rest's 2.0.0 latest page:

http://www.hug.rest/website/latest#gist32918334

Thanks!

~Timothy
