### ISSUE TITLE
running hug on pythonanywhere

### ISSUE THREAD

**Issue by simplynail** [timothycrosley/hug#487]
I have a problem running hug on pythonanywhere.com - I can't figure out how to point wsgi onto `__hug_wsgi__`. This should be a quick one, but it seems I'm still novice web developer :)

pythonanywhere has "username_pythonanywhere_com_wsgi.py" file where you setup the bindings for the app - you need to bind callable to `application` variable:
```

# +++++++++++ CUSTOM WSGI +++++++++++
# If you have a WSGI file that you want to serve using PythonAnywhere, perhaps
# in your home directory under version control, then use something like this:
#
import sys

path = '/home/username/myapps/dayassistant'
if path not in sys.path:
    sys.path.append(path)

# and here I'm trying to somehow bind hug_wsgi
import hug
import serve
from hug import __hug_wsgi__ as application
```
In hug docs 'quickstart' I found howto run hug via uWSGI from bash:
`uwsgi --http 0.0.0.0:8000 --wsgi-file first_step_3.py --callable __hug_wsgi__`
and tried to adjust it  but my approach doesn't seem to work as I get:
```
Error running WSGI application
ImportError: cannot import name '__hug_wsgi__'
File "/var/www/username_pythonanywhere_com_wsgi.py", line 73, in <module>
    from hug import __hug_wsgi__ as application
```

Further in the config file, example for Flask looks like:
```
# +++++++++++ FLASK +++++++++++
# Flask works like any other WSGI-compatible framework, we just need
# to import the application.  Often Flask apps are called "app" so we
# may need to rename it during the import:
#
#
#import sys
#
## The "/home/username" below specifies your home
## directory -- the rest should be the directory you uploaded your Flask
## code to underneath the home directory.  So if you just ran
## "git clone git@github.com/myusername/myproject.git"
## ...or uploaded files to the directory "myproject", then you should
## specify "/home/username/myproject"
#path = '/home/usename/path/to/flask_app_directory'
#if path not in sys.path:
#    sys.path.append(path)
#
## After you uncomment the line below, the yellow triangle on the left
## side in our in-browser editor shows a warning saying:
##     'application' imported but unused.
## You can ignore this error. The line is necessary, and the variable
## is used externally.
#from main_flask_app_file import app as application
#
# NB -- many Flask guides suggest you use a file called run.py; that's
# not necessary on PythonAnywhere.  And you should make sure your code
# does *not* invoke the flask development server with app.run(), as it
# will prevent your wsgi file from working.
```
anyone can help getting it running?

**Comment by Musilitar** [comment]
I think you are pretty close.

My file looks like this:

    import sys

    path = '/path/to/app'
    if path not in sys.path:
        sys.path.append(path)

    from api import __hug_wsgi__ as application

Here, `api` is `/path/to/app/api.py` which contains my `@hug.extend_api()` function

I think you are either trying to get the `__hug_wsgi__` from `hug` itself or your main file is also named `hug` which may cause some problems with your `import` statements (which I think are unnecessary).

Hope this helps!

**Comment by simplynail** [comment]
Hey, thank! 
That's what I was looking for, I kinda thought it might be connected to where 'last hug decorator' is used. 
so, I have following layout for project:
myapps/dayassistant/api/routes
in this package I have modules for different route categories and @hug.extend_api() them in __init__. py
so that I thought I could do import api.routes and have it all nicely bound for me to use it further

But I guess if in myapps/dayassistant/serve.py I do:
from api.routes import *

and in pythonanywhere wsgi file do:
import serve
application = serve.__hug_wsgi__

This cannot work? If not, is there a way to keep my folder structure and make it work?

**Comment by Musilitar** [comment]
Your folder structure sounds fine.

If I understood correctly I think you just have to to do

    import sys

    path = '/path/to/init.py'
    if path not in sys.path:
        sys.path.append(path)

    from init import __hug_wsgi__ as application

**Comment by simplynail** [comment]
No way to somehow import api.routes in base project folder and there bind __hug_wsgi__ to application? 
Just curious if I can somehow get binding for__hug_wsgi__ before code run

**Comment by cag** [comment]
> hug exposes a `__hug_wsgi__` magic method on every API module automatically

If your API module lives in `/path/to/my_api.py`, make sure `/path/to` is in your `sys.path` (which is where python searches when it is importing stuff), then

```python
import my_api
application = my_api.__hug_wsgi__
```

However, it sounds like you are trying to structure your code like a package: https://docs.python.org/3/tutorial/modules.html#packages

If you want to write `import api.routes`, your original sys.path code is correct, and you will want to make sure that an `__init__.py` file exists in the `api` and `route` folders. Then you can write

```python
from api.routes import init
application = init.__hug_wsgi__
```

If you rename `init.py` to `__init__.py`, you can write

```python
from api import routes
application = routes.__hug_wsgi__
```

Hope this clears things up.

**Comment by timothycrosley** [comment]
Thanks for submitting this question, it will be very helpful for us to prioritize documentation in the future,

I think @cag and @Musilitar have done a great job of answering this question, so I'm going to go ahead and mark it as closed, if you have any further concerns feel free to ask them here or withing a new issue.

Thanks!

~Timothy
