### ISSUE TITLE
Force HTTPS?

### ISSUE THREAD

**Issue by Musilitar** [timothycrosley/hug#490]
Is there any way to force HTTPS with Hug?
I know there are ways to do this in Django and Flask, but I'm unsure if this is possible in Hug and how I should do it.
Any help would be appreciated!

**Comment by cag** [comment]
I personally prefer letting `nginx` handle that. Hug does not handle any part of TLS, so setting your HTTPS policy should probably happen deeper in the stack. You can simply redirect, though if you are particularly insistent, you can use https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

Though it may render your domain unusable if you lose TLS support! Use with caution.

**Comment by timothycrosley** [comment]
I agree with @cag that I tend to do that at a different section of the stack, however, if you would like to do it within the application code - I've uploaded an example that shows how to accomplish it using an existing middleware: https://github.com/timothycrosley/hug/blob/develop/examples/force_https.py

Thanks and I hope this resolves your issue!

~Timothy

**Comment by Musilitar** [comment]
Thank you both for the detailed answers!
It would indeed be wiser to do this at the server level, I was just wondering because I'm hosting on Pythonanywhere and don't have direct access to those settings.
I'll ask them if it's possible to set it on the server, but if not now I have a way to do it with Hug.
Thanks again!
