### ISSUE TITLE
Global URL prefix

### ISSUE THREAD

**Issue by geoffjukes** [timothycrosley/hug#495]
Hi,

In ticket #210 it was mentioned that a feature slated for the 2.0 release, would be the ability to set a global URL prefix. Did that ever make it?

Hug assumes it will run from '/'. The API I am working on provides a super-set of features to an existing server (so '/' is in use), so I want to serve it from '/subdir'.

I use nginx, and the proxy_pass rewrite I outlined in https://github.com/timothycrosley/hug/issues/210#issuecomment-268910506 and the API serves just fine.

But the 'example' links are all incorrect, as they omit the '/subdir'.

How can I fix that, without having to add prefixes to all my endpoints?

Thanks,

Geoff

**Comment by timothycrosley** [comment]
Hi @geoffjukes,

Great question! You should be able to accomplish that now by doing:

```python
hug.API(__name__).http.base_url = '/subdir'`
```

As detailed in the implementing pull request here: 

https://github.com/timothycrosley/hug/pull/240/files

Your question will help me prioritize documentation,

Thanks!

~Timothy
