### ISSUE TITLE
webpage should update current version 2.2.0 -> 2.3.0

### ISSUE THREAD

**Issue by bernhardreiter** [timothycrosley/hug#503]
http://www.hug.rest/ still has 2.2.0 where we are at 2.3.0

**Comment by timothycrosley** [comment]
Thanks for pointing this out! This has now been updated

~Timothy

**Comment by bernhardreiter** [comment]
Thanks for maintaining hug as Free Software in the first place.
(I would have created a pull request, but did not quickly see where the webpage sources for this are saved.)
