### ISSUE TITLE
Question: Accessing HTTP Headers

### ISSUE THREAD

**Issue by DaytonG** [timothycrosley/hug#511]
Hey,

I'm trying to write a quick little program that can get all of the HTTP request headers for later processing. I've been struggling for a bit now, but haven't seen any way to actually do that.

Am I just missing it?

**Comment by timothycrosley** [comment]
Hi DaytonG,

Great question! The headers are available on the request object, which is made available simply by depending upon it:

```python
import hug


@hug.get()
def my_endpoint(request):
    return (request.headers)
```

The request object comes from Falcon, with it's full definition coming from here: http://falcon.readthedocs.io/en/stable/api/request_and_response.html

Hope this is helpful, and feel free to let me know if you have any further questions.

Thanks!

~Timothy
