### ISSUE TITLE
hug.__main__ error on Windows Server

### ISSUE THREAD

**Issue by ghost** [timothycrosley/hug#517]
Hello.

I just started trying to set up hug on a windows server 2012 R2 iis. I created a virtual enviroment and installed hug. If I try to run the happy_birthday example with the command:
python -m hug -f happy_birthday.py

I get an error with the message:
"C:\virtualenvs\foo\Scripts\python.exe: No module named hug.__ main __; 'hug' is a package an cannot be directly executed"

Why do I need the module here and how do I use it.

Greetings
Ket0ma

PS: If this is the wrong place to ask questions and for help just let me know.

**Comment by timothycrosley** [comment]
I haven't been able to reproduce this issue, closing it for now, but please let me know if you are still experiencing it and I will reopen

Thanks!

~Timothy
