### ISSUE TITLE
hug.exception does not work with hug.extend_api

### ISSUE THREAD

**Issue by milancurcic** [timothycrosley/hug#519]
In trying to add custom functionality when catching exceptions in hug, I discovered that `hug.exception` does not work if it is imported via `hug.extend_api`. Examples below:

This works:

test_exception1.py
```python
import hug

@hug.get('/hello')
def hello():
    return 1/0

@hug.exception()
def handle_exception(exception):
    print("hug handling exception")
```

This does not work in the sense that the exception is raised but not intercepted by `hug.exception`:

test_exception2.py
```python
import hug
import test_exception1

@hug.extend_api()
def api():
    return [test_exception1]
```

Don't know if this is a bug or a feature but thought it should be documented. This is for hug-2.3.0.

**Comment by timothycrosley** [comment]
Thanks for reporting this isssue! It has been fixed in develop and will make its way out with the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
A new version of hug `2.3.2` has been released that fixes this issue.

Thanks!

~Timothy
