### ISSUE TITLE
Hug doesn't install, but requires backports.typing

### ISSUE THREAD

**Issue by ssteinerx** [timothycrosley/hug#523]
Following the README instructions, Python 3.6.1:

* Create a new virtualenv
* Install hug with pip
* Run python interpreter

```
import hug
.../hug/hug/types.py", line 23, in <module>
    from backports.typing import Generic, TypeVar, GenericMeta
ModuleNotFoundError: No module named 'backports'
```
Simply running:

    pip install backports.typing

solves the issue.

**Comment by timothycrosley** [comment]
Thanks for pointing this out! This should now be fixed, and luckily, was in develop branch only - no one installing from pip should have ran into this.

Thanks! 

~Timothy

**Comment by ssteinerx** [comment]
@timothycrosley No problem, thanks for a great tool!  Looking forward to contributing more than pointing out a tiny oversight as I use it more.
