### ISSUE TITLE
cli returns booleans as strings and not return codes

### ISSUE THREAD

**Issue by teran-mckinney** [timothycrosley/hug#531]
I was expecting that returning True would exit with a status of 0 and returning with False would exit with a status of 1.

However, this is not the case:

```
$ cat trueorfalse.py3 
#!/usr/bin/env python3

import hug

API = hug.API('trueorfalse')


@hug.object(api=API)
class TRUEORFALSE(object):
    @hug.object.cli
    def true(self):
        return True

    @hug.object.cli
    def false(self):
        return False


if __name__ == '__main__':
    API.cli()
$ python3 trueorfalse.py3 
trueorfalse

Available Commands:

        - false
        - true

$ python3 trueorfalse.py3 true; echo $?
True
0
$ python3 trueorfalse.py3 false; echo $?
False
0
```

Is this intentional? Would you be open to a patch which changed this behavior?

Thank you!

**Comment by timothycrosley** [comment]
I would def be interested in a patch that adds that behavior, as I agree it's not intuitive. It would just need to be configurable somehow - which is why it's not the current behavior - the reason being that it should be valid for False to be returned without an error (say if you a service is running command line tool, it should be able to return True or False, without either representing an error state)

**Comment by teran-mckinney** [comment]
Thanks for getting back to me. I am looking through and this is definitely past the normal level of Python I write. OOP is pretty new to me, too.

I see in api.py you farm out the function that gets called, but does that directly call the function the user wrote, or does that happen down the road? I'm expecting a print() somewhere in hug/hug but none look quite like what I'd expect.

If you can point me to approximately where the function gets called (or a document that describes it) I can probably start adding that in.

**Comment by kootenpv** [comment]
This was biting me too. When I have an argument with default "active=False", in my case it became True as it is a string. But when you print it, it looks "okay". It's very difficult to spot it.

**Comment by tizz98** [comment]
@timothycrosley I'd like to work on this if possible. I think I have a working patch, however I'm not quite sure how to go about adding a test for the `CLIInterfaceAPI` to make sure that a non-zero exit code is returned in the proper situation

**Comment by timothycrosley** [comment]
@tizz98 sounds great! Thanks for being willing to take a stab at it. I'm not sure how to ensure a particular non-zero exit code is returned, but you can easily ensure something is outputted to stderr using capsys

**Comment by teran-mckinney** [comment]
@tizz98 thank you! Looking forward to using this in 2.3.3.
