### ISSUE TITLE
Issue with unicode characters in json response.

### ISSUE THREAD

**Issue by dustyny** [timothycrosley/hug#539]
I'm having an issue where Unicode encoding characters are ending up in my Hug response. When I save the dictionary to a file using JSON.dumps it doesn't have this issue. I spent a day trying to change the text to ASCII, UTF-8, removing punctuation, etc.. but no luck. I have a workaround for now but I'd like to know where I'm making my mistake. Any thoughts? 

`{
     "sentence_count": 40,
    "freq_terms": {
        "2015": 2,
        "self love": 6,
        "darling": 5,
        "trump": 4,
        "i\\xe2\\x80\\x99 m": 3,
        "\\xe2\\x80\\x9cradical self": 3,
        "cheat sheet": 2,
        "help guru": 2,
        "bind spell": 2,
        "trump bind": 2,
        "darling say": 2,
        "one": 2,
        "love workshop\\xe2\\x80\\x9d": 2,
        "doesn\\xe2\\x80\\x99 t": 2,
        "healing power": 2,
        "cast spell": 2,
        "self help": 2,
        "three": 2,
        "daily beast": 2,
        "new york": 2,
        "facebook": 2,
        "daily digest": 2,
        "athena": 2,
        "babe collective": 2,
        "\\xe2\\x80\\x9cradical self love workshop\\xe2\\x80\\x9d": 2,
        "feminine energy": 2
    },
    "freq_words": {
        "women": 12,
        "t": 8,
        "like": 8,
        "witch": 7,
        "self": 7,
        "Darling": 7,
        "world": 6,
        "things": 5,
        "Trump": 4,
        "witches": 4,
        "exercise": 4,
        "Darling\\xe2\\x80\\x99s": 4,
        "sense": 4,
        "time": 4,
        "magic": 4,
        "Daily": 4,
        "people": 4,
        "healing": 4,
        "help": 4,
        "said": 4,
        "online": 4,
        "energy": 4
    },
    "ngrams": {
        "\\xe2\\x80\\x9cRadical Self Love": 3,
        "self help guru": 2,
        "Self Love Workshop\\xe2\\x80\\x9d": 2,
        "Trump binding spell": 2
    },
    "entities": {
        "Darling": "PERSON",
        "Wizard of Oz": "",
        "Dorothy": "PERSON",
        "Kansas": "GPE",
        "Manhattan": "GPE",
        "\\xe2\\x80\\x9cRadical Self Love": "ORG",
        "Eastern": "ORG",
        "Donald Trump.\\\\nDarling": "PERSON",
        "American Horror Story Coven": "ORG",
        "Witch": "",
        "Gwyneth Paltrow\\xe2\\x80\\x99s": "PERSON",
        "Goop": "ORG",
        "Katy Perry": "PERSON",
        "Victoria Beckham": "PERSON",
        "Cara Delevingne": "PERSON",
        "Lena Dunham": "PERSON",
        "Adele": "PERSON",
        "Hollywood": "GPE",
        "Hocus Pocus": "ORG",
        "Craft": "ORG",
        "Charmed": "ORG",
        "J.K. Rowling\\xe2\\x80\\x99s Harry Potter": "PERSON",
        "Philosopher\\xe2\\x80\\x99s Stone": "",
        "Gregory Maguire\\xe2\\x80\\x99s Wicked": "PERSON",
        "Rowling\\xe2\\x80\\x99s Potter": "PERSON",
        "Wicked": "GPE",
        "\\\\nGet The Beast In Your Inbox": "WORK_OF_ART",
        "Daily Digest Start": "ORG",
        "Daily Beast": "",
        "Cheat Sheet A": "PERSON",
        "Privacy Policy Subscribe": "ORG",
        "Daily Digest": "",
        "Cheat Sheet": "PERSON",
        "\\xe2\\x80\\x9cRadical": "",
        "\\xe2\\x80\\x9cWitchling Oracle Cards\\xe2\\x80\\x9d\\xe2\\x80\\x94a": "ORG",
        "Witchlings": "GPE",
        "magic,\\xe2\\x80\\x9d Darling says to whoops": "PERSON",
        "cheers.\\\\nWe": "GPE",
        "Summer Solstice\\xe2\\x80\\x94which": "ORG",
        "Tracy Anderson\\xe2\\x80\\x99s arm": "PERSON",
        "\\xe2\\x80\\x9cRadical Self Love Workshop\\xe2\\x80\\x9d": "PERSON",
        "Stevie Nicks": "LOC",
        "moment\\xe2\\x80\\x94visualize": "ORG",
        "Instagram": "GPE",
        "Don\\xe2\\x80\\x99t": "PERSON",
        "teachings\\xe2\\x80\\x94feminine": "ORG",
        "New York City": "GPE",
        "Brooklyn": "GPE",
        "Williamsburg": "GPE",
        "\\xe2\\x80\\x9ctaking": "GPE",
        "Kali": "GPE",
        "Hindu": "NORP",
        "Mother": "PERSON",
        "Robin Lee": "PERSON",
        "BABE Collective": "GPE",
        "resistance.\\\\n\\xe2\\x80\\x9cThe": "NORP",
        "here,\\xe2\\x80\\x9d Stacy Schiff": "ORG",
        "Witches Salem": "",
        "Daily Beast of": "",
        "Schiff": "PERSON",
        "Athena": "ORG",
        "us.\\xe2\\x80\\x9d\\\\nIndeed": "ORG",
        "Alex Jones\\xe2\\x80\\x99": "",
        "Rush Limbaugh\\xe2\\x80\\x99s": "PERSON",
        "Jones": "PERSON",
        "Infowars": "ORG",
        "Hillary Clinton \\xe2\\x80\\x9c\\xe2\\x80\\x98regularly\\xe2\\x80\\x99": "PERSON",
        "Limbaugh": "PERSON",
        "Clinton": "PERSON",
        "Azealia Banks": "ORG",
        "I\\xe2\\x80\\x99": "ORG",
        "Jews": "NORP",
        "SEERS": "ORG",
        "DIVINERS": "ORG",
        "Lana Del Ray": "PERSON",
        "Trump": "PERSON",
        "Gala Darling": "PERSON",
        "Facebook": "GPE",
        "California": "GPE",
        "Texas": "GPE",
        "England": "GPE",
        "New York": "GPE",
        "Mother Earth,\\xe2\\x80\\x9d": "ORG",
        "Sarah Wilson": "PERSON",
        "Martha\\xe2\\x80\\x99s Vineyard": "GPE"
    }
}`

**Comment by timothycrosley** [comment]
Hi @dustyny, 

Thanks for reporting this issue! You're not making any mistakes, in new versions of the built-in json module, the `dump` function takes an `ensure_ascii` parameter that defaults to `False` and does the conversion your seeing above. You can get the behaviour you want in the current release by doing:

```python
@hug.default_output_format()
def augmented(data, **kwargs):
    return hug.output_format.json(data, ensure_ascii=False, **kwargs)
```

I've also updated the code base to default to setting ensure_ascii to False which will be applied in the next release.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
A new version of hug `2.3.2` has been released that fixes this issue.

Thanks!

~Timothy
