### ISSUE TITLE
Is it possible to change API parameter name without changing the name in Python?

### ISSUE THREAD

**Issue by justinas-kazanavicius** [timothycrosley/hug#540]
I need to have a parameter named `global` on my API endpoint, however, `global` is a built-in keyword in python. Is it possible to use an annotation or something, so that people who issue requests can use `global` as a parameter, but Python variable would be named `global_` so that it can be used in code?

**Comment by timothycrosley** [comment]
While this was possible in the current release, it was hackish and not in a clean consistent way. This is an important feature to have, so I took the time to implement a clean solution:

In the next release (or the current development branch) you can optionally define a remapping per interface type:

```python
hug.local(api=hug_api, map_params={'local_id': 'record_id'})
    @hug.cli(api=hug_api, map_params={'cli_id': 'record_id'})
    @hug.get(api=hug_api, map_params={'id': 'record_id'})
    def pull_record(record_id: hug.types.number):
        return record_id
```

Hopefully, this fully addresses your concern.

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
A new version of hug `2.3.2` has been released that fixes this issue.

Thanks!

~Timothy
