### ISSUE TITLE
Accessing API version inside a route

### ISSUE THREAD

**Issue by ch0k0bn** [timothycrosley/hug#547]
I'm facing a problem where between two versions of my API, only my object schema has changed.

I could have two marshmallow schemas and two (almost) identical routes that each invoke their respective schema but it will duplicates a lot of code/schemas.

```python
@hug.get('/{id}', versions=1)
def get_objects(id: uuid):
     obj = load_from_db(id)
     return object_schema_v1.dump(obj)

@hug.get('/{id}', versions=2)
def get_objects(id: uuid):
     obj = load_from_db(id)
     return object_schema_v2.dump(obj)
```

So i was thinking of having a schema that handle versioning to only have one route for both versions like this for example:

```python
@hug.get('/{id}')
def get_objects(id: uuid):
     api_version = <a way to get the api version called>
     object_schema.context = {"api_version": api_version}
     obj = load_from_db(id)
     return object_schema.dump(obj)
```

For that purpose i need to pass the version number to my schema (as a context for dumping) but i didn't find any way of easily getting it.

**Comment by ZeFr3d** [comment]
Have you tried the `hug_current_api` built-in directive?

You could do something like this:
```python
@hug.get('/{id}', versions=(1,2))
def get_objects(hug_current_api, id: uuid):
     object_schema.context = {"api_version": hug_current_api.api_version}
     obj = load_from_db(id)
     return object_schema.dump(obj)
```

**Comment by ch0k0bn** [comment]
Works perfectly. Thanks a lot.
