### ISSUE TITLE
request_middleware Question

### ISSUE THREAD

**Issue by MrRJ45** [timothycrosley/hug#55]
I've just come across hug as I'm writing a new API and it looks simple, but very effective :)

I'm currently adding authentication using request_middleware as this:

```python
import hug
from falcon import HTTP_FORBIDDEN

@hug.request_middleware()
def process_data(request, response):
        if 'X-API-Key' not in request.headers:
                response.body='403 Forbidden'
                response.status=HTTP_FORBIDDEN

@hug.get('/test', versions=1)
def test(text):
        print(text)
        return {'text': text}
```

This works fine, and returns a 403, however it continues to process the endpoint (I see the text on the console).

Is there a (sane) way to stop this from happening?

**Comment by timothycrosley** [comment]
Hi @MrRJ45,

Sorry I didn't get to this question earlier! How did you resolve this issue?

Thanks!

~Timothy
