### ISSUE TITLE
Version ignored in classes

### ISSUE THREAD

**Issue by esafak** [timothycrosley/hug#552]
The tests in [test_url_inheritance](https://github.com/timothycrosley/hug/blob/7469736597ff011a23fac0e1aba6d6f2619bb370/tests/test_route.py#L45) also pass with or without **any** version!

**Comment by timothycrosley** [comment]
You are correct that versioning is broken within Class routers, this is now fixed in develop and will now make it into the next release:

https://github.com/timothycrosley/hug/pull/560/files

Thanks for reporting!

~Timothy

**Comment by timothycrosley** [comment]
A new version of hug `2.3.2` has been released that fixes this issue.

Thanks!

~Timothy
