### ISSUE TITLE
Can hug be used over https?

### ISSUE THREAD

**Issue by dstromberg** [timothycrosley/hug#553]
Hi.

I'm thinking about using hug for a project that would involve transmitting some sensitive data.  Can hug do https?

Thanks.

**Comment by ch0k0bn** [comment]
I run hug with uwsgi (see [hug doc](https://github.com/timothycrosley/hug#running-hug-with-other-wsgi-based-servers)) behind nginx.
Nginx handle the ssl part and transfers request to uwsgi  (see  [uwsgi doc](http://uwsgi-docs.readthedocs.io/en/latest/Nginx.html#nginx-support)). Works perfectly.

**Comment by timothycrosley** [comment]
@ch0k0bn is correct. HTTPS is not something meant to be handled as part of the WSGI application layer, but by the WSGI HTTP Server (uWSGI, Gunicorn, etc..) you use to run it in production.

**Comment by mansonami** [comment]
@ch0k0bn Could you help me to show how to configure https:******/hello with hug?

**Comment by mansonami** [comment]
> @ch0k0bn is correct. HTTPS is not something meant to be handled as part of the WSGI application layer, but by the WSGI HTTP Server (uWSGI, Gunicorn, etc..) you use to run it in production.

Could you help me to show how to configure https:******/hello with hug?
