### ISSUE TITLE
Weird behaviour with strings in versions parameter

### ISSUE THREAD

**Issue by prizos** [timothycrosley/hug#555]
Hey, I appreciate that versions is intended to be int as per docs but I am encountering some odd behaviour when I accidentally used strings.

example:

```python
import hug

@hug.post('/echo', versions=str(1))
def echo(text):
    return text
```

```bash
curl -d'text=lala' -X POST http://localhost:8000/v1/echo
{
    "404": "The API call you tried to make was not defined. Here's a definition of the API to help you get going :)",
    "documentation": {
        "version": "1",
        "versions": [
            "1"
        ],
        "handlers": {
            "/echo": {
                "POST": {
                    "outputs": {
                        "format": "JSON (Javascript Serialized Object Notation)",
                        "content_type": "application/json"
                    },
                    "inputs": {
                        "text": {
                            "type": "Basic text / string value"
                        }
                    }
                }
            }
        }
    }
}
```

with a log of:

```127.0.0.1 - - [17/Sep/2017 20:31:52] "POST /v1/echo HTTP/1.1" 404 721```

if I try a GET though, I just get the expected Method Not Allowed:

```127.0.0.1 - - [17/Sep/2017 20:31:31] "GET /v1/echo HTTP/1.1" 405 0```

Am I missing something and strings just end up on a different path ?
Same results with ```@hug.get``` etc.

**Comment by timothycrosley** [comment]
Thanks for reporting! I've verified that this issue is indeed a bug in the current implementation, and I've resolved it here:

https://github.com/timothycrosley/hug/pull/557

Thanks!

~Timothy

**Comment by timothycrosley** [comment]
A new version of hug `2.3.2` has been released that fixes this issue.

Thanks!

~Timothy
