### ISSUE TITLE
allow_origins should split multiple allowed locations to multiple lines.

### ISSUE THREAD

**Issue by mikko-m** [timothycrosley/hug#563]
At the moment [allow_origins](https://github.com/timothycrosley/hug/blob/a9ae986ae5ab9588e665d1cba1b71e662a076f17/hug/routing.py#L237
) joins the multiple allowed locations to single line. This doesn't work in many cases.

Instead of listing multiple allowed locations in one header line multiple header lines should be added.

https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains 

https://stackoverflow.com/questions/35303654/cors-header-access-control-allow-origin-does-not-match-but-it-does

edit: splitting to multiple headers could be wrong based on some comments from stackoverflow. It seems that the code should inspect if the origin is allowed and then send back the origin domain if it is allowed.

**Comment by mikko-m** [comment]
Here is prototype of working middleware with multiple allowed origins (could be very easily hacked to support regexps etc.)

`allowed_origins = ['http://domain1.com', 'http://www.domain2.com']                                                                                                                                  
                                                                                                                                                                                              
@hug.response_middleware()                                                                                                                                                                    
def cors_middleware(request, response, resource):                                                                                                                                             
    pp.pprint(request.headers)                                                                                                                                                                
    if 'ORIGIN' in request.headers:                                                                                                                                                           
        origin = request.headers['ORIGIN']                                                                                                                                                    
        if origin in allowed_origins:                                                                                                                                                         
            response.set_header('Access-Control-Allow-Origin', origin)                                                                                                                        
`

**Comment by nicolaspascual** [comment]
Can I take this?

**Comment by timothycrosley** [comment]
I'm okay with that! Would appreciate the help as long as @mikko-m hasn't started working on a pull request?

**Comment by mikko-m** [comment]
I have not. Feel free to copy the code.

**Comment by nicolaspascual** [comment]
I'm on it

**Comment by coolbung** [comment]
I'd suggest to review the implementation once more, since the recommended way of doing the origin header is different - https://stackoverflow.com/a/1850482/720709
