### ISSUE TITLE
Support for running from a script

### ISSUE THREAD

**Issue by glennra** [timothycrosley/hug#57]
I want to be able to run/debug my services in eclipse/pydev. I faked it by doing this in my hug API file:

    if __name__ == '__main__':
        import sys
        from hug import run
        # run.terminal() gets its args from sys.argv so give it what it expects
        sys.argv[0] = "hug"
        sys.argv.extend(['-f', __file__])
        run.terminal()
and it seems to work.

Is there a better way that I have missed?

**Comment by timothycrosley** [comment]
Hi @glennra,

Yes there is a better way! And you where so close to it :)

    import hug
    if __name__ == '__main__':
        import sys
        hug.run.server(sys.modules[__name__])

Let me know if this works for you

Thanks!

~Timothy

**Comment by glennra** [comment]
Hi @timothycrosley,

That doesn't do what I want. It just '''Returns a WSGI compatible API server for the given Hug API module''' but doesn't call some sort of run_forever(). I see from the source of run.terminal() that I need to pass that to make_server and then call serve_forever() on the returned httpd object. It seems easier to just modify sys.argv.

**Comment by timothycrosley** [comment]
@glennra,

You are correct, and sorry for the confusion! I've added quicker way to start hug servers to the framework to the API, merged into develop, in preparation for the next release. You can see an example of it's usage here:

https://github.com/timothycrosley/hug/blob/develop/examples/quick_server.py

Let me know if this would work for your needs.

Thanks!

~Timothy

**Comment by glennra** [comment]
Almost, but why do you need to use __hug__? Couldn't you just add hug.run.serve()?
Also people may want to set the port, etc, so serve should probably take the same parameters that are set with the command line switches in hug.run.terminal(). Would it work if you factored out the server running part from hug.run.terminal() and allowed it to be called with parameters and then call this new function from hug.run.terminal() after parsing sys.argv?
So it would be still a single line for my use case, something like:
    hug.run.serve(port=8888, version=2) # etc

**Comment by timothycrosley** [comment]
Hi @glennra,

The `__hug__.serve` method does take the same arguments including port, and no_documentation. The reason the functionality doesn't existing on hug.run is because determining what module a function is being ran from is not straight forward or performant.

Thanks!

~Timothy

**Comment by glennra** [comment]
Ok, I see. Thanks. I'll switch to using the develop branch.

**Comment by timothycrosley** [comment]
This has officially been released in 1.3.0

Thanks!

~Timothy
