### ISSUE TITLE
Suggestion: argument to disable start-up (intro) message

### ISSUE THREAD

**Issue by MattBSG** [timothycrosley/hug#579]
On different environments I install on I have to currently remove the intro message from the module as so my logs are not cluttered up. Possibly we could get an argument when starting to not display it?

**Comment by timothycrosley** [comment]
I've gone ahead and implemented a `--silent` flag that can be used to when starting a hug instance to keep the intro message from showing up. This will make its way into the next release.

Thanks!

~Timothy
