### ISSUE TITLE
Charset not set for Content-Type application/json

### ISSUE THREAD

**Issue by ivdelchev** [timothycrosley/hug#590]
I am new to Hug and want to try it for my next project, but I am hitting an issue. It seems Hug sets Content-Type "application/json" instead of "application/json; charset=utf-8" for the json output handler and this causes Chrome & Safari to display a non-ascii string in the output like this:

{"error": "Could not parse Ã¼brigens"}

I am not 100% sure if that is the issue but with other libraries (e.g. bare bones Falcon), the issue is not there. Have you observed this and how can I fix it?

**Comment by timothycrosley** [comment]
Thanks for reporting! This has been fixed in develop and will make it's way out in the next release
