### ISSUE TITLE
Newlines are replaced with \n

### ISSUE THREAD

**Issue by glennra** [timothycrosley/hug#60]
When I use this method:

    @hug.get()
    def newline():
        s = """this is a string
    with a newline
    """
        return s

I get the following output from `http://localhost:8000/newline`:

    "this is a string\nwith a newline\n"

Is it possible to prevent the newline being replaced?

**Comment by timothycrosley** [comment]
Hi @glennra, 

If you want to return text and not JSON data (which get's serialized, thus showing \n) it should be sufficient just to change the output type to text:

    @hug.get(output=hug.output_format.text)
    def newline():
    s = """this is a string
with a newline
    """
    return s

Let me know if this works, thanks!

~Timothy

**Comment by glennra** [comment]
Yes that works, thanks. (And now that I know what to look for I see that it is in the documentation.)

**Comment by timothycrosley** [comment]
Awesome, glad to know it worked :) closing this issue now
