### ISSUE TITLE
Set API endpoint log level

### ISSUE THREAD

**Issue by carlos4ndre** [timothycrosley/hug#609]
Hi,

I new to Hug and so far it has been great!

I have a couple of endpoints I do not wish to log their request/response, e.g., `/_health`, `/_doc`.
Would it be possible to set those endpoints with a lower logging level? As of now, they are generating a significant amount of traffic, that I'm not interested in. 

Looking at the source code [here](https://github.com/timothycrosley/hug/blob/a0a1ec83d0bbc43bebc64eb3b645297db35619d7/hug/middleware.py#L99-L105), it appears the request/response is always logged with `info` level, not sure there is a way around this. I'm open to other suggestions.

Thanks,
Carlos

**Comment by ZeFr3d** [comment]
Have you tried to create a logger named "hug" (with a log level set to warning) and creating your LogMiddleware instance without passing it a logger object?

**Comment by carlos4ndre** [comment]
By creating a custom **LogMiddleware** I managed to filter out the endpoints I'm not interested to log.
I think this should be good.

Thanks for your support!
