### ISSUE TITLE
apr_socket_recv: Connection reset by peer (104)

### ISSUE THREAD

**Issue by bruceforlearn** [timothycrosley/hug#625]
Hello guys,

I use hug make a API, but it can not load ab test like this

`root@ubuntu:/home/txt# ab -n 5000 -c 1000 -p tx.txt http://XX.XX.XXX.177:8000/get_response?user_input=
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking XX.XX.XXX.177 (be patient)
Completed 500 requests
Completed 1000 requests
apr_socket_recv: Connection reset by peer (104)
Total of 1464 requests completed

root@ubuntu:/home/txt# ab -n 2000 -c 500 -p tx.txt http://XX.XX.XXX.177:8000/get_response?user_input=
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking XX.XX.XXX.177 (be patient)
Completed 200 requests
Completed 400 requests
Completed 600 requests
Completed 800 requests
Completed 1000 requests
Completed 1200 requests
Completed 1400 requests
Completed 1600 requests
apr_socket_recv: Connection reset by peer (104)
Total of 1606 requests completed
`

**this is my hug script** 

`#!/usr/bin/env python# coding: utf-8
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import hug

bot = ChatBot("chatbot")

conv = open('kb.txt', 'r').readlines()

bot.set_trainer(ListTrainer)

bot.train(conv)

@hug.get()
def get_response(user_input):
    response = bot.get_response(user_input).text
    return {"response":response}
`

how can I improve load concurrency to 10000?

thank you

**Comment by bruceforlearn** [comment]
server's cpu and mem are very rich
top - 11:15:13 up  1:03,  3 users,  load average: 0.00, 0.00, 0.00
Tasks: 248 total,   1 running, 247 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.1 sy,  0.0 ni, 99.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16425492 total, 15814692 free,   239340 used,   371460 buff/cache
KiB Swap: 16774140 total, 16774140 free,        0 used. 15872096 avail Mem

**Comment by bruceforlearn** [comment]
root@localhost:/home/py# sysctl -p
net.ipv4.tcp_syncookies = 0
net.ipv4.tcp_max_syn_backlog = 10240
net.ipv4.tcp_max_tw_buckets = 20480

**Comment by bruceforlearn** [comment]
I solved it

**Comment by hrdxwandg** [comment]
@bruceforlearn  i also meet the error, can you share your method to solve it?

**Comment by mslee89** [comment]
Hi, @hrdxwandg
 
To solve that, you should increase value of net.ipv4.tcp_max_syn_backlog.

**Comment by hrdxwandg** [comment]
@mslee89 
ok, thanks

**Comment by sanshuipige** [comment]
I increased value of net.ipv4.tcp.max_syn_backlog, but it fail , I set a lot of params with socket ,such as max_syn_backlog、somaxconn like this, but  all invalid, I am at a loss. if you have a good idea ,pleasse send gmail to sanshuipige@gmail.com, thank you!

**Comment by sanshuipige** [comment]
I increased value of net.ipv4.tcp.max_syn_backlog, but it fail , I set a lot of params with socket ,such as max_syn_backlog、somaxconn like this, but  all invalid, I am at a loss. if you have a good idea ,pleasse send gmail to sanshuipige@gmail.com, thank you!
