### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by swilcox** [timothycrosley/hug#631]
Due to possible changes with `asyncio`, it appears hug may have a problem with python 3.7.x. Tested using Python 3.7.0beta2.

```hug --help
Traceback (most recent call last):
  File "/usr/local/bin/hug", line 7, in <module>
    from hug import development_runner
  File "/usr/local/lib/python3.7/site-packages/hug/__init__.py", line 36, in <module>
    from hug import (authentication, directives, exceptions, format, input_format, introspect,
  File "/usr/local/lib/python3.7/site-packages/hug/route.py", line 29, in <module>
    import hug.api
  File "/usr/local/lib/python3.7/site-packages/hug/api.py", line 37, in <module>
    from hug._async import asyncio, ensure_future
  File "/usr/local/lib/python3.7/site-packages/hug/_async.py", line 30
    ensure_future = asyncio.async  # pragma: no cover
                                ^
SyntaxError: invalid syntax```

**Comment by cmin764** [comment]
Confirmed with stable Python 3.7.0. Can be this solved? I just can run `hug` due to this SyntaxError. Thanks!

**Comment by swilcox** [comment]
This appears to be fixed by some changes made by @timothycrosley a few months ago: https://github.com/timothycrosley/hug/commit/22e7de475d4a150abe356b175a6d8aa14b8418bf but until another release is made, you'll have to resort to pip installing from source or tweaking it yourself.

**Comment by markuman** [comment]
In the meantime, the best way (for me) is to install the current dev version in your project folder

`pip install -t $(pwd) git+https://github.com/timothycrosley/hug`

**Comment by wimglenn** [comment]
@timothycrosley  Any chance for a release soon?

**Comment by hnykda** [comment]
Yeah, new release would be appreciated

**Comment by hnykda** [comment]
@timothycrosley I know we are annoying, but couldn't you at least move the privileges to someone else if you don't have time for this?

**Comment by timothycrosley** [comment]
I'll start on this today. No one here or in this thread is being in any way annoying (except for perhaps myself). I've been focused on physical community building (https://lovelicton.com/) over the last few months and have had a hard time balancing responsibilities. I'll do my best to get better. I'd also be interested in hearing other people who would be interested in being a joint maintainer or part of a group of maintainers of this project to avoid this happening in the future. Bonus points if you live in the PNW / Seattle area so we could discuss next

Thanks to everyone here for keeping to push on this, it's important!

~Timothy

**Comment by timothycrosley** [comment]
Just pushed out 2.4.1 with Python 3.7 support.

Thanks!

~Timothy

**Comment by hnykda** [comment]
Awesome! Thanks for such a quick reply and explanation, it actually helps :slightly_smiling_face:  and it is totally understandable.
