### ISSUE TITLE
Can Talons be used for authentication?

### ISSUE THREAD

**Issue by richiverse** [timothycrosley/hug#68]
https://github.com/talons/talons

**Comment by timothycrosley** [comment]
Hi @richiverse: 

Yes it should be compatible! I haven't tested Talons in particular, but hug is designed to be compatible with all Falcon middle-ware components:

   __hug__.add_middleware(FalconMiddleware())

as shown in the middleware sections here https://github.com/timothycrosley/hug#building-blocks-of-a-hug-api. Let me know if you have any issues with this, and if it solves your issue.

Thanks!

~Timothy

**Comment by richiverse** [comment]
cool thx! Awesome project!
