### ISSUE TITLE
Posting with mashmallow schema

### ISSUE THREAD

**Issue by jshwelz** [timothycrosley/hug#723]
@incognick @timothycrosley How can I map the body json with a mashmallow schema like:
def post(input: userschema, response): and use input instead of body

**Comment by leovujanic** [comment]
@jshwelz I believe you could use something like this to map params:
```python
@hug.post("/test", map_params={"body": "input"})
def post(input: userschema, response):
    return input
```

**Comment by jshwelz** [comment]
> @jshwelz I believe you could use something like this to map params:
> 
> ```python
> @hug.post("/test", map_params={"body": "input"})
> def post(input: userschema, response):
>     return input
> ```

that works thanks
