### ISSUE TITLE
CORS Middleware and Python 3.7

### ISSUE THREAD

**Issue by franzmango** [timothycrosley/hug#724]
Hi!

I think I stumbled across a compatibility issue with Python 3.7 that has to do with re.sub() behavior change (https://docs.python.org/3/library/re.html#index-36) in middleware.py line 131.

https://github.com/timothycrosley/hug/blob/develop/hug/middleware.py#L131

I patched it for myself by replacing `if re.match(re.sub(r'/{[^{}]+}', '/[\w-]+', route) + '$', reqpath):` with `if re.match(re.sub(r'/{[^{}]+}', r'/[\\w-]+', route) + '$', reqpath):`.

Maybe my fix is missing something, but I thought I would let you know :)

**Comment by GhostofGoes** [comment]
Could you open this as a PR?

**Comment by franzmango** [comment]
Opened the PR
