### ISSUE TITLE
`extend_api()` fails if methods come from different modules

### ISSUE THREAD

**Issue by akaihola** [timothycrosley/hug#742]
I have both a `GET` and a `POST` handler for the same endpoint, and both have a substantial amount of code. For that reason, I'd like to separate them into two modules.

When using `extend_api()` with these two modules, only one of the handlers becomes available.

**Comment by akaihola** [comment]
See [this commit](https://github.com/akaihola/hug/commit/5e278aa1fbd1f1a2b3bb91bd089f5908987baed7) for a failing test case.

**Comment by altunyurt** [comment]
I believe #689 is related
