### ISSUE TITLE
Feature request: An easy way to change the default CLI output format

### ISSUE THREAD

**Issue by akaihola** [timothycrosley/hug#746]
See timothycrosley/hug_yaml#4 for two different ways to set the default output format for all CLI API functions. A native way to set the default in Hug would be nice. 

This probably should touch the `hug.interface.CLI.outputs` property to add a way to obtain a custom default output format instead of the hard-coded `hug.output_format.text`.

**Comment by timothycrosley** [comment]
This should be fixed in the latest release (2.4.4), you can now set a default for CLI in a simular mannor as done for http:

per API:

```
hug.API(__name__).cli.output_format = my_custom_output_format

# OR

@hug.default_output_format(cli=True, api=hug_api)
def my_custom_formatter(data):
    return data_after_my_custom_transformation

```

globally:

```
hug.defaults.cli_output_format

# OR

@hug.default_output_format(cli=True, api=hug_api, apply_globally=True)
def my_custom_formatter(data):
    return data_after_my_custom_transformation
```

Thanks!

~Timothy

**Comment by akaihola** [comment]
Hi Timothy,

The `OUTPUT_FORMATS.md` file seems to be out of sync with your description above:
- missing examples for the all of the arguments of the `@hug.default_output_format` decorator
- missing examples for `hug.defaults.output_format` and `hug.defaults.cli_output_format`
- should probably point out that `hug.defaults.*` must be modified before importing API modules with which to extend the API, in order for the default to affect the sub-APIs

In case you're not already working on this, I can take a stab at it.

**Comment by timothycrosley** [comment]
That would be great, I appreciate it!
