### ISSUE TITLE
404 output doesn't obey `hug.defaults.output_format`

### ISSUE THREAD

**Issue by akaihola** [timothycrosley/hug#753]
I'm setting 
```python
hug.defaults.output_format = hug.output_format.accept(
    {'application/json': hug.output_format.json,
     'text/yaml': hug_yaml.output_format.yaml,
     'application/x-yaml': hug_yaml.output_format.yaml},
    default=hug_yaml.output_format.yaml)
```

All my API endpoints now return YAML by default. The output format for responses also correctly changes according to the `Accept:` header.

However, the API description included in 404 responses is still always JSON, no matter whether I omit or include an `Accept:` header.

**Comment by timothycrosley** [comment]
This is fixed in Release 2.4.6: https://github.com/timothycrosley/hug/releases/tag/2.4.6

Thanks!

~Timothy
