### ISSUE TITLE
Multiple parallel requests not working

### ISSUE THREAD

**Issue by Spenhouet** [timothycrosley/hug#856]
I am really confused right now.

I would expect every web framework to handle multiple requests in parallel but for some reason this does not work with hug. What am I missing?

Given the following implementation (`endpoint.py`):

```
import hug
import time

@hug.get()
def sleep(body):
    time.sleep(20)
```

Started with `hug -f endpoint.py`.

If I open two different browser windows and request `http://127.0.0.1:8000/sleep` in both of them, then I would expect both to finish after 20 seconds (I did also test this with totally different clients - it is not a client issue).

But in reality they run sequentially one after the other and take 40 seconds (the following requests were started at 22:48:20):

```
127.0.0.1 - - [05/May/2020 22:48:40] "GET /sleep HTTP/1.1" 200 4
127.0.0.1 - - [05/May/2020 22:49:00] "GET /sleep HTTP/1.1" 200 4
```

What is going on? That can't be right. Could someone explain what I'm doing wrong?

**Comment by underrun** [comment]
hug does not currently support async requests ... but even then you would need something like `await asyncio.sleep(20)` instead of `time.sleep(20)` and your function would need to be async.

the underlying issue is that hug uses falcon which is wsgi - asgi is a newer model which supports async. this will be fixed if either falcon shifts to asgi or if we port hug to use something like starlette.

the way to get parallelism right now with hug is to use multiple processes with uwsgi for example that your web server can spread requests over.

**Comment by Spenhouet** [comment]
@underrun I think you are confusing terminology here. This has nothing to do with asychronous / synchronous function calls. WSGI does by no means imply that requests are handled sequentially. This has nothing to do with WSGI vs ASGI. That is a totally different issue.

This issue is about the underlying web server not handling parallel requests. If that is currently not a bug or a user error on my part then this is a major draw back of hug or actually a total killer. I can't imagine any use-case where this is acceptable.

**Comment by Spenhouet** [comment]
In fact, I tested the above code in falcon and it works absolutely as expected.

```
import falcon
import time


class SleepResource(object):

    def on_get(self, req, resp):
        time.sleep(20)
        resp.status = falcon.HTTP_200
        resp.body = ('\nfinished')


app = falcon.API()
sleep = SleepResource()
app.add_route('/sleep', sleep)
```

I started the web server with `waitress-serve --port=8000 endpoint:app`.

Both requests nearly end at the same time i.e. both requests are run in parallel (as expected).

This is not an issue of falcon. It is an issue with hug.
Do I have to set a specific startup parameter for the web server?

**Comment by Peter200lx** [comment]
You can run HUG with `waitress-serve` if you wish:
https://hugapi.github.io/hug/#running-hug-with-other-wsgi-based-servers

`waitress-serve --port=8000 endpoint:__hug_wsgi__`
```
$ date;http get http://localhost:8000/sleep -b;date
Wed 06 May 2020 12:33:48 AM PDT
null

Wed 06 May 2020 12:34:09 AM PDT
```
```
$ date;http get http://localhost:8000/sleep -b;date
Wed 06 May 2020 12:33:49 AM PDT
null

Wed 06 May 2020 12:34:10 AM PDT
```
The fact that you're getting multiple non-asynchronous calls working at the same time is coming from `watress-serve` acting as a WSGI server.

**Comment by Spenhouet** [comment]
> The fact that you're getting multiple non-asynchronous calls working at the same time is coming from waitress-serve acting as a WSGI server.

Yes, sure. But that should not be a matter of "getting it to work", that should be the default behavior. Where is the use in starting a WSGI server that is unable to handle parallel request?

My issue stands. Hugs underlying WSGI server currently seems unable to handle parallel requests. I would consider this a major bug since it renders this WSGI server useless.

**Comment by jay-tyler** [comment]
Development servers are a convenience provided for quick sanity checking,
and not for production use.

Also, from the docs:

> Final step: Production HTTP use
> Finally, it's important to note that it's generally never a good idea to
> use a development server (like hug's, Flask's, etc.) directly in
> production. Instead, a WSGI-compatible server (such as uwsgi or Gunicorn)
> is recommended. Every hug API that contains an http endpoint automatically
> exposes a `__hug_wsgi__` WSGI-compatible API - making integration of our
> above example a breeze:
>

This sort of alacarte approach is super common in web frameworks, and
almost every web application uses different execution contexts for
development vs production deployment.

**Comment by Spenhouet** [comment]
@jay-tyler Thanks for the clarification. That makes total sense. It was not obvious to me that the default hug WSGI server is only for development.
